### ISSUE TITLE
Q: Real-time video processing

### ISSUE THREAD

**Issue by SeungHunJeon** [NVlabs/FoundationPose#10]
Thank you for sharing your astonishing work!

As you mentioned, the computation time (20-30Hz) ensures real-world adaptability. 

Hence, I'm curious about how we can transition this model to estimate 6D pose in the live-streaming video.
(The provided demo handles the recorded video)

**Comment by wenbowen123** [comment]
you can simply replace the data from the datareader to your own camera stream. 
https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L48

**Comment by Shanzhaguoo** [comment]
Very good job! Thank you！
What would be the effect if this work is applied to a scene (for example, in SLAM tasks)? I wonder if the authors have conducted any related experiments?

**Comment by wenbowen123** [comment]
@Shanzhaguoo  We haven't tried this. But this is definitely an interesting direction!

**Comment by sheslkw** [comment]
I tried to use camera stream as you mentioned to replace the data from datareader. But I got wrong. When i=0, I use the precaptured rgb and depth images and the corresponding mask. And I changed the parameter of pose = est.track_one(rgb=color, depth=depth, K=reader.K, iteration=args.track_refine_iter) from i = 1. 
How should I do to make it correct with camera stream?
