### ISSUE TITLE
Save learnt custom dataset after inference

### ISSUE THREAD

**Issue by grth25** [NVlabs/FoundationPose#101]
Hi,
First of all I want to thank you for your work. It is working really well on custom data I have tested so far.

I am new to pytorch and I am not sure if it is possible to save the learnt weights of new objects in inference or if I have to run inference everytime I want to use the pose estimation? 

Thanks!

**Comment by wenbowen123** [comment]
Hi I'm not sure if I understand. What do you mean by saving the learnt weights? When you run inference, the weights are frozen and not trained anymore.

**Comment by grth25** [comment]
Okay, so when the weights are frozen, is there a possiblity to save the frozen weights to a file? And is it possible to extend the saved file by inference on a new object at a later time?

To explain my problem in more detail: I would like to use your program to perform a pose estimation on several objects. I want to have a model that has the possibility to add new objects at a later time. Accordingly, I would like to have the possibility to flexibly extend a pose estimation model. Is this possible using inference as in the demo scripts? Or how would I do this?

It may be a simple question but I've never worked with inference before so I am not so sure how it really works. I hope that I did specify it a bit better.

**Comment by wenbowen123** [comment]
there is no need to save weights files. You can create multiple `est` like [here](https://github.com/NVlabs/FoundationPose/blob/69db1c3d3555a6f4176a36bcd662dcc72a057903/run_demo.py#L41), where each of them is using a different object's mesh. Or you can call [reset_object](https://github.com/NVlabs/FoundationPose/blob/69db1c3d3555a6f4176a36bcd662dcc72a057903/estimater.py#L44) to adapt the est to a new object.

**Comment by grth25** [comment]
Okay, thank you a lot for your help. I will try this out.
