### ISSUE TITLE
There are many instances of the same in a scene, how do you separate them all

### ISSUE THREAD

**Issue by yyyyzy1** [NVlabs/FoundationPose#104]
Hello,  When there are many different instances of the same object in the scene, how do you estimate their attitude?

**Comment by wenbowen123** [comment]
you dont need special treatment. As long as you have 2D instance segmentation masks and send each of them to FoundationPose, it should work.

**Comment by lpy523** [comment]
Is it possible to track two objects at the same time?

**Comment by wenbowen123** [comment]
> Is it possible to track two objects at the same time?

yes, you just need to create two instances here https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L41 for different objects.

**Comment by lpy523** [comment]
Thank you for your reply! I have another question: 

is it possible to perform the same operation in the original code of Bundlesdf? If so, does it mean that after I create two instances and input the RGB, Depth and Mask of both objects, the model will output the tracking results of both objects at the same time? 

And Is there a way to calculate the relative positional relationship between the two objects?

thanks again！




> > Is it possible to track two objects at the same time?
> 
> yes, you just need to create two instances here https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L41 for different objects.

**Comment by lpy523** [comment]
> > Is it possible to track two objects at the same time?
> 
> yes, you just need to create two instances here https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L41 for different objects.

Thank you for your reply! I have another question:

is it possible to perform the same operation in the original code of Bundlesdf? If so, does it mean that after I create two instances and input the RGB, Depth and Mask of both objects, the model will output the tracking results of both objects at the same time?

And Is there a way to calculate the relative positional relationship between the two objects?

thanks again！

**Comment by wenbowen123** [comment]
if only one side of the object is visible when running FoundationPose, then yes, you can just reconstruct that side when running BundleSDF. @lpy523

**Comment by lpy523** [comment]
Sorry to bother you again, what I mean is that if I only use the code [https://github.com/NVlabs/BundleSDF](url) from the BundleSDF raw repository, is there a similar operation that would allow me to track two different instances at the same time?Thanks again! @wenbowen123

**Comment by lpy523** [comment]
> > Is it possible to track two objects at the same time?
> 
> yes, you just need to create two instances here https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L41 for different objects.

Sorry to bother you again, what I mean is that if I only use the code [https://github.com/NVlabs/BundleSDF](https://github.com/NVlabs/FoundationPose/issues/url) from the BundleSDF raw repository, is there a similar operation that would allow me to track two different instances at the same time?Thanks again! @wenbowen123

**Comment by yyyyzy1** [comment]
> if only one side of the object is visible when running FoundationPose, then yes, you can just reconstruct that side when running BundleSDF. @lpy523
If the instance objects are all the same, do I still need to register all the time, and can I omit some steps? Otherwise it feels like time consuming

**Comment by yyyyzy1** [comment]
> if only one side of the object is visible when running FoundationPose, then yes, you can just reconstruct that side when running BundleSDF. @lpy523

For example, can I initialize and optimize the attitude of the first target and only optimize the attitude of the other targets
