### ISSUE TITLE
Hello, may I ask how to convert the bmp depth map exported by Hikang camera into the depth map we need

### ISSUE THREAD

**Issue by wsq1010** [NVlabs/FoundationPose#106]

**Comment by wsq1010** [comment]
![图片](https://github.com/NVlabs/FoundationPose/assets/108775107/6f600be7-bce8-4c65-a8c4-9de9d9689083)

**Comment by wenbowen123** [comment]
are you able to get the depth map in meters from that camera?

**Comment by wsq1010** [comment]
Hello, I use Hikon MV-DLS600P camera exported depth map looks different from Intel RealSense

**Comment by wenbowen123** [comment]
For that you'd need to consult with their customer support on how to get the depth map in meters.
