### ISSUE TITLE
Performance on a symmetrical object

### ISSUE THREAD

**Issue by TomiAijala** [NVlabs/FoundationPose#107]
Hello. I am having some issues when performing pose estimation and tracking on a symmetrical, textureless, cylinder like object. During the tracking phase the pose estimate will spin around the cylinder’s longitudinal axis and will not stay consistent when the object is kept in place. 

Is there a way to prevent this type of behaviour by defining symmetries for the object or by some other means?

**Comment by wenbowen123** [comment]
Hi, for objects like that, the pose is non-unique and each of the spinned pose would make sense. Does it affect your downstream task? Unless inferring from the background, the model does not know if the object truly rotates around the symmetric axis.

**Comment by TomiAijala** [comment]
Thank you for your answer. This type of behavior does not affect my task. I was just wondering if it is possible to prevent this type of behavior easily somehow, but it does not seem like there is a simple solution for it.

**Comment by liuchangji** [comment]
Such kind of non-unique object has infinitely many solutions. So you need to do a post-processing after getting results from foundationPose. For example, temporal filter.

**Comment by zhaowangji** [comment]
> Such kind of non-unique object has infinitely many solutions. So you need to do a post-processing after getting results from foundationPose. For example, temporal filter.

Hello, could you tell me more of these solutions?

**Comment by mathanprasannakumar** [comment]
Hi @TomiAijala , 

Have you found solution for handling the symmetrical non-unique objects , as i am observing similar issue

**Comment by mathanprasannakumar** [comment]
Hi @wenbowen123 ,

I am simply trying to estimate the pose of the black cube , initially generated mesh using bundle sdf and then tried to estimated pose via foundation pose , but for every registration i am getting estimated pose coordinate axis which is not consistant.
