### ISSUE TITLE
poor performance in rotation

### ISSUE THREAD

**Issue by eunseon02** [NVlabs/FoundationPose#109]
plz watch from 0:17

https://github.com/NVlabs/FoundationPose/assets/108911413/aafdc265-18dd-40d0-b748-1914e7a5df81

I am using #44 code and bundlsdf for generating dataset.

this is debug folder
https://drive.google.com/drive/folders/1m1ya5ZLovTmB1o6oRxs7cXV6EHTyK5Ch?usp=drive_link

**Comment by wenbowen123** [comment]
![image](https://github.com/NVlabs/FoundationPose/assets/23078192/7e30d72f-137e-4df2-af8b-0d6c4680b45e)
Hi, I'd suggest to improve the model first. You can expose difference faces when capturing the video to let bundlesdf build all faces.
