### ISSUE TITLE
how is the performance of the version released

### ISSUE THREAD

**Issue by cypacjy** [NVlabs/FoundationPose#11]
considering that  the version released is without training on diffusion-augmented data. Slight performance degradation is expected.i wonder how this version with released pretrained data can be

**Comment by wenbowen123** [comment]
You can refer to table 6 in the paper. For practical application, it still works well in most cases empirically. You are welcome to try on the example data, which includes multiple challenges such as motion blur, extreme rotations/flipping, severe occlusions.
