### ISSUE TITLE
custom data object pose estimate wrong.

### ISSUE THREAD

**Issue by LiYan0306** [NVlabs/FoundationPose#110]
When I tested pose estimate by model-base method, I met an unknow wrong as follows.

https://github.com/NVlabs/FoundationPose/assets/72531073/1576e568-f27e-4aaa-b863-bf513824f43f

And here are my input data:
https://drive.google.com/file/d/10Lt-Qrlwd2CO0F1VjMxakm1W-ZbgDqk6/view?usp=sharing

**Comment by wenbowen123** [comment]
Hi, your model is in mm, please scale it to meters.

**Comment by Hotsburp** [comment]
Hi @wenbowen123, silly question from me but could i clarify the scaling to meters portion that you mentioned?

For example, i am using Solidworks to produce a CAD (default units is mm), the original object is 10cm x 10cm by 10cm = 100mm x 100mm x 100mm. 

Does scaling mean 100m x 100m x 100m for the model (Magnitude same but just mm -> m) or 0.1m x 0.1m x 0.1m (Change default units from mm to m)?

**Comment by wenbowen123** [comment]
you need to make the object 0.1m. As you can see in your viz, the 3D box is too large. You need to scale the 3D model smaller.
