### ISSUE TITLE
ycbv dataset confusion

### ISSUE THREAD

**Issue by cheny110** [NVlabs/FoundationPose#111]
When I run model free few-shot version on ycbv dataset, I get confused on the dataset pathes passed to the param.
What's the different between YCB-Video and YCB_Video?

**Comment by wenbowen123** [comment]
where are you referring to?

**Comment by cheny110** [comment]
In Official README file, **Run on public datasets (LINEMOD, YCB-Video)** section, the  given example command for model-free running is:
```
python bundlesdf/run_nerf.py --ref_view_dir /mnt/9a72c439-d0a7-45e8-8d20-d7a235d02763/DATASET/YCB_Video/bowen_addon/ref_views_16 --dataset ycbv

python run_ycb_video.py --ycbv_dir /mnt/9a72c439-d0a7-45e8-8d20-d7a235d02763/DATASET/YCB-Video --use_reconstructed_mesh 0
```
So what's the difference between **DATASET/YCB_Video/** and **DATASET/YCB-Video**

**Comment by wenbowen123** [comment]
thanks for pointing this out! It was a typo, now corrected.
