### ISSUE TITLE
How to Remove Miniconda Dependency in Docker

### ISSUE THREAD

**Issue by ssapsu** [NVlabs/FoundationPose#114]
Hello! I'm truly impressed with your fantastic project and grateful that you’ve made it open source! 
I've been using it by building with a Dockerfile, and I have a question about why it’s set up to run on Miniconda. 
Using Miniconda seems to consume a lot of resources, which tends to make the program more cumbersome. 
Could you advise on how to build it without using Miniconda?

**Comment by ssapsu** [comment]
Hey everyone, I've successfully created my own Dockerfile and developed a ROS2 node that's compatible with Humble. I've also managed to connect it to Isaac Sim. Here’s a video demonstrating how it works. I'm really excited about this open source project
Thanks so much for making it available! 
Check out the video here: [https://youtu.be/ldfOBDbt8rA](url)

**Comment by StevePotter** [comment]
Hey ssapsu, can you elaborate on "consume a lot of resources"?  As far as I know, conda basically isolates the python environment and sets up symlinks for commands like `python`, which shouldn't have an effect on runtime.  What am I missing?

I agree that conda commands everywhere makes the dockerfile more difficult to read, but I'm unaware of it having an perf impact.

I do think that the project should be updated to install packages via requirements.txt or a conda environment.yml.  I was planning on doing that in the near future as part of my initiative to improve docker images (see my PR #81)

**Comment by ssapsu** [comment]
Good afternoon, StevePotter

I was mistaken in thinking that Conda uses a lot of resources.

Despite this, I created a Docker container to isolate the environment, but I don’t understand why I should install Conda in it. Isn’t it enough that the environment is already isolated?

Actually, my concern started because ROS2, the robot operating system, has been discouraging the use of Anaconda together with the system’s default Python from Eloquent onwards. So, I had no choice but to opt out of using Conda.

**Comment by wenbowen123** [comment]
We used conda because it's still helpful to manage the versions among different packages. You can modify the dockerfile to skip conda steps and use pip to install all the packages.
