### ISSUE TITLE
几何图像形状无法被正确识别

### ISSUE THREAD

**Issue by 52THANOS** [NVlabs/FoundationPose#115]
![3f91e1c2b2888da4bfffc8653aa05bd](https://github.com/NVlabs/FoundationPose/assets/117810189/774fe0d0-b9a4-4ed5-bad2-7aa92118d494)
![39a8916a689a38f059eb0cae61f9c50](https://github.com/NVlabs/FoundationPose/assets/117810189/ba59569c-d4e7-44ab-898a-e118e9057c72)
为什么refiner似乎识别不出我的形状

**Comment by wenbowen123** [comment]
what is the unit of your mesh? Is it in meter?

**Comment by 52THANOS** [comment]
> what is the unit of your mesh? Is it in meter?

i think is meter

**Comment by wenbowen123** [comment]
it does not look right. You can measure this in meshlab. Another thing worth checking is the segmentation mask

**Comment by 52THANOS** [comment]
> it does not look right. You can measure this in meshlab. Another thing worth checking is the segmentation mask

yes，my mask is wrong
