### ISSUE TITLE
Pose conditioned rendering before Pose Selection takes up a lot of CUDA memory.

### ISSUE THREAD

**Issue by GavinYang5** [NVlabs/FoundationPose#116]
![img_v3_02ao_1d56091c-367e-498d-9633-ee7630ae09ag](https://github.com/NVlabs/FoundationPose/assets/93421835/9463530b-16ca-4a1a-bf0e-fcf36ac129f4)
I have observed that in the Pose conditional rendering step, a significant amount of CUDA memory will be occupied. Is this normal? Is there any good way to reduce the usage of CUDA memory?
This seems to involve using `Kornia.geometry.transform`

**Comment by GavinYang5** [comment]
@wenbowen123

**Comment by GavinYang5** [comment]
I found it useful to put the tensor on the CPU before using `kornia.geometry.transform.warp_perspective`, but it would increase the computation time. I actually want to know the minimum amount of CUDA memory needed to run FoundationPose. And is there any room for optimization. Thank you, looking forward to your reply

**Comment by wenbowen123** [comment]
Hi, putting to CPU is a nice way to do it. Another way to do is to do divide the whole batch into mini batches to run that part.

**Comment by liuchangji** [comment]
> I found it useful to put the tensor on the CPU before using `kornia.geometry.transform.warp_perspective`, but it would increase the computation time. I actually want to know the minimum amount of CUDA memory needed to run FoundationPose. And is there any room for optimization. Thank you, looking forward to your reply

Hello. I met the same problem as yours. Could you please share your code which use CPU part?
