### ISSUE TITLE
    error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Aki-zel** [NVlabs/FoundationPose#117]
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Obtaining file:///home/ydz/Documents/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  Running setup.py develop for common
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [41 lines of output]
        /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        running develop
        /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running egg_info
        creating common.egg-info
        writing common.egg-info/PKG-INFO
        writing dependency_links to common.egg-info/dependency_links.txt
        writing top-level names to common.egg-info/top_level.txt
        writing manifest file 'common.egg-info/SOURCES.txt'
        reading manifest file 'common.egg-info/SOURCES.txt'
        writing manifest file 'common.egg-info/SOURCES.txt'
        running build_ext
        error: [Errno 2] No such file or directory: ':/usr/local/cuda:/usr/local/cuda/bin/nvcc'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [41 lines of output]
    /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'extra_cflags'
      warnings.warn(msg)
    /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
      warnings.warn(msg)
    running develop
    /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/ydz/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    creating common.egg-info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    writing manifest file 'common.egg-info/SOURCES.txt'
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    error: [Errno 2] No such file or directory: ':/usr/local/cuda:/usr/local/cuda/bin/nvcc'
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xuyb123** [comment]
@Aki-zel Hi, how did you fix this problem?

**Comment by Aki-zel** [comment]
> @Aki-zel您好，您是如何解决这个问题的？

cuda_home needs to be set in the system environment

**Comment by anan-fighting** [comment]
> > [@Aki-zel](https://github.com/Aki-zel)您好，您是如何解决这个问题的？
> 
> cuda_home needs to be set in the system environment

Can you please explain how to provide the CUDA-HOME variable in the virtual environment? I can't find a file similar to CUDA-XX at all
