### ISSUE TITLE
Follow-up on Issue 83: Tracking drifting towards the end fo the samples

### ISSUE THREAD

**Issue by KomputerMaster64** [NVlabs/FoundationPose#119]
This is in continuation of the Issue #83

> the bottom two images show a significant jump which is not very suitable for tracking. You can increase the camera frame rate if possible. Otherwise, you can also try with higher iter
> 
> https://github.com/NVlabs/FoundationPose/blob/fce37c86be33ee49cf0b46ee29ed26d613521d6d/run_demo.py#L21

Hi @wenbowen123 

I am sorry for the delayed response.
I ran the experiments with values for `track_refine_iter` variable ranging from `2` to `50`, however it was observed that the tracking invariably drifted towards the end samples (last 15 to 20 percent of the video).
I would be delighted to share the files.

Regards,
Prabhav

__
**Edit**: I am sharing the failure case for the case with `track_refine_iter` variable set to `50`.

**Remarks**: For the shown case, the tracking failure happends towards the end of the samples. The tracking is optimal till image `1714129813249.png` i.e. for the first `410` samples (Total of `619` image samples).

**Additional Remarks**: This is an improvement it to the first case where `track_refine_iter` variable was set to `2`, and the tracking was optimal only upto the `157` image samples.

I have uploaded the new `FoundationPose_demo_05_eri-5_tri-50.zip` file [here](https://drive.google.com/file/d/1bqj42pr4Ph7Cf0nTEFO6uv1ehjScgCvi/view?usp=sharing) (this is corresponding to the `track_refine_iter` variable set to `50`) in the [Google Drive Folder](https://drive.google.com/file/d/1J8hJEVitQQnlRl6cdscq1vfZv7vStF5X/view?usp=sharing).

**Question/Note**: The total size of the debugging directories for the 49 experiments is 7 GB. It would be great if you could confirm if it is required to share all of the experiments' files.

__
The last frame with the correct tracking (top), and the frame after which the trakcing was not optimal (bottom).
![1714129813249](https://github.com/NVlabs/FoundationPose/assets/68422504/c30283f6-0cba-40f7-848c-ddb11967bfdc)
![1714129813295](https://github.com/NVlabs/FoundationPose/assets/68422504/8ee08512-112c-411a-a323-c8bf5a67975d)

**Comment by wenbowen123** [comment]
I checked your logs. The object is moving too fast at 1714129813249. Your camera frequency is not fast enough.

**Comment by KomputerMaster64** [comment]
Thank you for the response. I will check for better camera hardware. Do you recommend performing actions at a slower pace?

**Comment by wenbowen123** [comment]
did you check how much fps is the camera images? The upper bound of realsense is 30hz, but sometimes it could be lower than that. In the video, you are ejecting the cube to perform free-form sliding, that moment the motion is really big.

**Comment by BXZZcj** [comment]
> This is in continuation of the Issue [#83](https://github.com/NVlabs/FoundationPose/issues/83)
> 
> > the bottom two images show a significant jump which is not very suitable for tracking. You can increase the camera frame rate if possible. Otherwise, you can also try with higher iter
> > 
> >   
> >     
> >       [FoundationPose/run_demo.py](https://github.com/NVlabs/FoundationPose/blob/fce37c86be33ee49cf0b46ee29ed26d613521d6d/run_demo.py#L21)
> >     
> >     
> >          Line 21
> >       in
> >       [fce37c8](/NVlabs/FoundationPose/commit/fce37c86be33ee49cf0b46ee29ed26d613521d6d)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >            parser.add_argument('--track_refine_iter', type=int, default=2)
> 
> Hi [@wenbowen123](https://github.com/wenbowen123)
> 
> I am sorry for the delayed response. I ran the experiments with values for `track_refine_iter` variable ranging from `2` to `50`, however it was observed that the tracking invariably drifted towards the end samples (last 15 to 20 percent of the video). I would be delighted to share the files.
> 
> Regards, Prabhav
> 
> __ **Edit**: I am sharing the failure case for the case with `track_refine_iter` variable set to `50`.
> 
> **Remarks**: For the shown case, the tracking failure happends towards the end of the samples. The tracking is optimal till image `1714129813249.png` i.e. for the first `410` samples (Total of `619` image samples).
> 
> **Additional Remarks**: This is an improvement it to the first case where `track_refine_iter` variable was set to `2`, and the tracking was optimal only upto the `157` image samples.
> 
> I have uploaded the new `FoundationPose_demo_05_eri-5_tri-50.zip` file [here](https://drive.google.com/file/d/1bqj42pr4Ph7Cf0nTEFO6uv1ehjScgCvi/view?usp=sharing) (this is corresponding to the `track_refine_iter` variable set to `50`) in the [Google Drive Folder](https://drive.google.com/file/d/1J8hJEVitQQnlRl6cdscq1vfZv7vStF5X/view?usp=sharing).
> 
> **Question/Note**: The total size of the debugging directories for the 49 experiments is 7 GB. It would be great if you could confirm if it is required to share all of the experiments' files.
> 
> __ The last frame with the correct tracking (top), and the frame after which the trakcing was not optimal (bottom). ![1714129813249](https://github.com/NVlabs/FoundationPose/assets/68422504/c30283f6-0cba-40f7-848c-ddb11967bfdc) ![1714129813295](https://github.com/NVlabs/FoundationPose/assets/68422504/8ee08512-112c-411a-a323-c8bf5a67975d)

Hello, you may try this improved version of FoundationPose to see if it resolves your issue:
[FoundationPose++: Very Simple Tricks Boost FoundationPose Performance in High-Dynamic Scenes](https://github.com/teal024/FoundationPose-plus-plus)
