### ISSUE TITLE
depth_enhanced and ob_in_cam

### ISSUE THREAD

**Issue by shzcuber** [NVlabs/FoundationPose#121]
Is there a guideline on how to get these two pieces of data for the reference images?

**Comment by wenbowen123** [comment]
depth_enhanced is just depth image. ob_in_cam is the object pose for the ref images.

**Comment by EquilibriaW** [comment]
so what is the difference between depth and depth_enhanced?

**Comment by wenbowen123** [comment]
depth_enhanced added some minor interpolation on top of depth. But this turns out to not make a big difference. For someone's own application, just using depth is fine.
