### ISSUE TITLE
How to reproduce on Windows ？

### ISSUE THREAD

**Issue by TPF0628** [NVlabs/FoundationPose#123]
how to install pin==2.7.0 ?
how can I fix this error "AttributeError: 'NoneType' object has no attribute 'cluster_poses'" on windows?
Thank u

**Comment by mehamednews** [comment]
I get this error `AttributeError: 'NoneType' object has no attribute 'cluster_poses'"` on linux as well (using the docker image).
It's related to a `mycpp` package.

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/issues/89
@mehamednews

**Comment by TPF0628** [comment]
Thank you!  I've fixed the issue

**Comment by ronnypollak** [comment]
Hello @TPF0628 did u make it run on Windows and if so how? I already tried running it with WSL but ran into various issues.

**Comment by TPF0628** [comment]
Be sure to compile the MyCPP file on Windows
