### ISSUE TITLE
Foundation pose under BundleSDF generated CAD

### ISSUE THREAD

**Issue by JRvilanova** [NVlabs/FoundationPose#125]
Hi,

I am having a problem when tracking a driller that I generated my own CAD model with BundleSDF. I attach the mask, the image and this model, so that you can see the problem. I am aligning correctly the frames and all that stuff related to capturing with realsense. Then, I think that the problem is related to CAD model, as the tracking is not good at all. Can you provide help with that?

![color](https://github.com/NVlabs/FoundationPose/assets/150953922/8488ddf0-1714-4b57-b70f-4e538968cfc4)

![ob_mask](https://github.com/NVlabs/FoundationPose/assets/150953922/ead3b205-0e5f-4024-9dd3-3b2929e72e4d)

![Screenshot from 2024-05-14 15-34-49](https://github.com/NVlabs/FoundationPose/assets/150953922/27175ffb-e27a-4f8d-be79-5e79c6803b8b)

Thanks in advance!

**Comment by liuchangji** [comment]
As so far your CAD model has no color texture.

**Comment by byran-wang** [comment]
![image](https://github.com/NVlabs/FoundationPose/assets/16728958/90eac00e-0409-4031-99f7-62cd72f582bf)
You can follow suggestions in the picture to modify your BundleSDF code to get the texture CAD model.
