### ISSUE TITLE
debug for run_linemod.py is not completely implemented

### ISSUE THREAD

**Issue by robotcreator** [NVlabs/FoundationPose#128]
I have downloaded the LINEMOD dataset from here: https://bop.felk.cvut.cz/datasets/.

To run `run_linemod.py` I have used this command:

`python run_linemod.py --linemod_dir /home/path/to/LINEMOD --use_reconstructed_mesh 0`

It basically works fine and prints some predictions on the terminal, but I have found that there seems to be no functionality implemented in `run_linemod.py` to actually store the predictions properly, as compared to `run_demo.py`.
Looking at the `debug` variable, only level 3 is implemented, level 1 and 2 are missing. Is that intended?
In my opinion, this should be added in order to check quickly if you get accurate predictions. 
The same holds for `run_ycb_video.py`.

**Comment by wenbowen123** [comment]
duplicate https://github.com/NVlabs/FoundationPose/issues/33

**Comment by robotcreator** [comment]
Thanks for the feedback! I tested the additions proposed in #33 and got it running with a little buxfixing. I will comment on it in #33. This issue can be closed.
