### ISSUE TITLE
Running without mask initial guess

### ISSUE THREAD

**Issue by Woz4tetra** [NVlabs/FoundationPose#13]
Awesome demo! I've managed to get the docker container to run on the mustard demo with some minor tweaks.

I noticed the demo requires a manually defined mask to provide an initial guess of the object's pose. This there a way to run the demo without providing this initial mask?

**Comment by wenbowen123** [comment]
FoundationPose accepts various forms. Other than mask, you can also provide a 2D box or a single point. All can be converted to the binary mask in the same format as the segmentation mask. 

You can obtain those with tools such as SAM, Mask-RCNN, CNOS.

**Comment by monajalal** [comment]
@wenbowen123 

In order to get real-time inference on the novel object of interest, is there a way to streamline this with your docker?

**Comment by wenbowen123** [comment]
@monajalal you can hook up with tools such as SAM, Mask-RCNN, CNOS. This is beyond the scope of this work, and different users may have different desired workflows to get the mask.
