### ISSUE TITLE
Cuda error while using YCB Dataset images with run_demo.py

### ISSUE THREAD

**Issue by Sar-thak-3** [NVlabs/FoundationPose#130]
While using YCB Dataset on `run_demo.py`, it generates this error
```
RuntimeError: Cuda error: 2[cudaMalloc(&m_gpuPtr, bytes);
```
I changed `get_depth()`, `get_color()` and `get_mask()` according to the YCBReader but still the error persists.

**Comment by wenbowen123** [comment]
what is your GPU memory?
