### ISSUE TITLE
The lost of tracking

### ISSUE THREAD

**Issue by Ginger-X** [NVlabs/FoundationPose#131]
The first half of the target object is tracked well, but after masking or moving out, the position estimation is no longer carried out correctly, any ideas on how to solve this, thanks!

**Comment by wenbowen123** [comment]
do you have a video showing this?

**Comment by Ginger-X** [comment]
yes, I have. I know that the position estimation is inevitably poor when there is heavy occlusion, but do you have any thoughts on tracking the position again when the target object reappears, e.g. with the help of the detection model. Also, I would like to ask how the AR effect is achieved, can you provide demo code, thanks a lot!

https://github.com/NVlabs/FoundationPose/assets/65015349/e682e24c-f266-4efa-ad84-a8a006985c99

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/issues/136 maybe related

**Comment by Ginger-X** [comment]
Thank you for your reply, it will be very helpful. Also, I would like to ask how the AR effect is achieved as shown in demo, can you provide example code or describe the tools used to achieve this? thanks a lot!

**Comment by wenbowen123** [comment]
@Ginger-X unfortunately this part involves some other internal modules beyond FoundationPose, which is not sharable for this point. But once you have the 6D pose, the other parts are only on the engineering side.
