### ISSUE TITLE
Pose Estimation on the First Frame is Out of Scale

### ISSUE THREAD

**Issue by nirajkark07** [NVlabs/FoundationPose#132]
Hello! 

Congratulations on your work.

I am running the algorithm on my own custom data using an intel real sense d455 camera, following the procedures in #44. I am running into an issue where the scale of the model on the first frame of pose detection is wrong. However, at some point the pose detection corrects itself.

See the below video. At the 17 second mark, pose estimation is correct.

[Screencast from 2024-05-20 11-08-04_trimmed.webm](https://github.com/NVlabs/FoundationPose/assets/34893732/8e26a9e2-d716-4ee3-81e8-b86e5e87190b)

The CAD model that I'm using was created on blender.

![image](https://github.com/NVlabs/FoundationPose/assets/34893732/dfa88cf3-c534-4049-8cf4-886dbff86215)

I have uploaded my debug folder to google drive. Would you be able to take a look at it?

https://drive.google.com/drive/folders/15-y2nAmWByZ0QwsIf7RsetOJ5RBhPt_9?usp=sharing

Thank you!

**Comment by wenbowen123** [comment]
You have two issues:
1. The model texture is not loaded, same as https://github.com/NVlabs/FoundationPose/issues/94#issuecomment-2086866695
2. The depth value is missing on the object somehow. You can viz the generated point cloud scene_complete.ply in the debug folder

**Comment by nirajkark07** [comment]
Thank you for your comments. I will try out and update accordingly. I have a another issue (as I'm quite new to linux, haha). I will open another form for it.
