### ISSUE TITLE
A question about model training

### ISSUE THREAD

**Issue by byran-wang** [NVlabs/FoundationPose#134]
Thank you so much for your excellent work! I have run this code successfully, and the demo is amazing.

I have some questions about the model training. There are two models in FoundationPose: one for pose refinement and another for pose selection. In the pose estimation stage, the pose refinement model samples 252 camera points. Do these 252 sampled camera points still exist in the model training? From my perspective, there are still 252 sampled camera points because they need to supply pose hypotheses to the pose selection stage.

Looking forward to your reply very much. Thank you again for your work.

**Comment by wenbowen123** [comment]
the sampled poses at test time can be arbitrary. During training, we randomly sample the poses. So we didn't keep them consistent between training and testing. Though if we keep the consistency between the training and testing, it might help a bit I guess.

**Comment by byran-wang** [comment]
OK, I get it. Thanks.
