### ISSUE TITLE
How to test on RGB without training needed?

### ISSUE THREAD

**Issue by DavidJimenezS** [NVlabs/FoundationPose#135]
I've read the paper and found that you have a method to take as input RGB images and it is able to predict the pose.
However, I've been seeking for that code but haven succeed on it. Do you think, you can help me with that?

Thanks in advance for your help

**Comment by wenbowen123** [comment]
Hi, we are going to push a commit that supports RGB only soon. Stay tuned.

**Comment by DavidJimenezS** [comment]
Great, I'll keep an eye on it. 
Amazing job.

**Comment by ronnypollak** [comment]
@wenbowen123 Can you give a rough estimate when you will release that code? Thank you for your work!

**Comment by nilsmelchert** [comment]
@wenbowen123 Any news on the rgb only version?
