### ISSUE TITLE
does the model not have the ability to distinguish the two sides

### ISSUE THREAD

**Issue by yzy2001** [NVlabs/FoundationPose#140]
For a batch of the same objects, placed on the table, but the positive and negative angles are different, I send them to the model in batches. Although the model can recognize the posture of different angles, the Z-axis direction of the objects placed on the front and the objects placed on the back are the same, does the model not have the ability to distinguish the two sides?

**Comment by yzy2001** [comment]
![f jpg](https://github.com/NVlabs/FoundationPose/assets/81019232/e87ec22e-70f3-425a-a819-12fa9fadb93c)
![z jpg](https://github.com/NVlabs/FoundationPose/assets/81019232/c87f59a4-2383-4d06-987f-77cbf038c3f1)
the z-axis of the object faces the same direction

**Comment by wenbowen123** [comment]
Hi, is the object symmetric for both sides?

**Comment by yzy2001** [comment]
> Hi, is the object symmetric for both sides?

![ams](https://github.com/NVlabs/FoundationPose/assets/81019232/3caf3451-542e-4ed5-aced-60b498dc77b5)
![asm](https://github.com/NVlabs/FoundationPose/assets/81019232/b592f67c-1624-4b11-b50c-d0378119b5f9)
this is the obj file of the object , with different features on both sides

**Comment by yzy2001** [comment]
> Hi, is the object symmetric for both sides?

![ams](https://github.com/NVlabs/FoundationPose/assets/81019232/b67eefd8-a614-41e2-ac26-b9d92f67273a)
![asm](https://github.com/NVlabs/FoundationPose/assets/81019232/5951c1f9-e2fe-4eb9-bcf0-80bdf37b25f9)
This is the obj file of the object, with different features on the front and back, some letters engraved on the front, and some screws on the back

**Comment by wenbowen123** [comment]
from the RGB looks like your object is red, but your 3d model is gray?

**Comment by yzy2001** [comment]
> from the RGB looks like your object is red, but your 3d model is gray?

oh! must the supplied cad file be consistent with the real thing in all aspects, including color,size,texture?

**Comment by wenbowen123** [comment]
for a better performance, you need to make color consistent.
