### ISSUE TITLE
How to Train the Neural Object Field?

### ISSUE THREAD

**Issue by AbdulrahmanAlsumeri** [NVlabs/FoundationPose#141]
Thanks a lot for this wonderful work. I would like to know how to train the Neural Object Field using the LLM-aided pipeline proposed in the paper?. You mentioned that the weights of this network can't be released.

**Comment by wenbowen123** [comment]
Hi, the neural object field is trained per scene not on the LLM-aided sim data. See https://github.com/NVlabs/FoundationPose/blob/main/bundlesdf/run_nerf.py
