### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by yuanxiaoyu1** [NVlabs/FoundationPose#143]
Great job, but I have some questions about the coordinate systems. What is the coordinate system for estimating the 6DOF pose? For the RealSense camera, which one should be used: camera_link, camera_color_optical_frame, or camera_depth_optical_frame?
This is crucial for the accurate operation of the robot.

**Comment by wenbowen123** [comment]
use `camera_color_optical_frame`, and make sure you are using the topic of depth aligned to rgb. See https://github.com/NVlabs/FoundationPose/issues/44#issuecomment-2048141043

**Comment by yuanxiaoyu1** [comment]
Thanks for your quick reply !
