### ISSUE TITLE
Why is the score greater than 100, And whether the pose estimation score is 100 percent

### ISSUE THREAD

**Issue by yuyang19** [NVlabs/FoundationPose#151]
Thanks for your excellent work,
I ran the run_demo.py on my own data, but the result is so poor, and I found that the output score would be greater than 100；
like this:
_**[register()] sorted scores: tensor**_([ 145.8125, 145.7812, 148.7812, 145.7188, 145.6250, 145.6250, 145.6250, 
 145.6250, 145.5938, 145.5938, 145.5938, 145.5938, 145.5625, 145.5625,
...
...
144.8125, 144.8125, 144.7812, 144.7812, 144.7812, 144.7500,  1447188 ])

I don't understand what the score means.
Thank you very much for your reply.

**Comment by wenbowen123** [comment]
the score does not have any absolute meaning. Only relative score comparison between poses make sense. So >100 doesn't really mean anything. You can refer to troubleshooting section to see other possible problems. https://github.com/NVlabs/FoundationPose?tab=readme-ov-file#troubleshooting

**Comment by yuyang19** [comment]
ok, thank you very much.
