### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by shirokalu** [NVlabs/FoundationPose#155]
Hello, your work is very impressive and has been of great help to me.

However, I have a question regarding creating my own dataset. Do I necessarily need the pose of the target relative to the camera when creating a custom dataset? Additionally, I am interested in your other work, BundleSDF. Could I use the results of BundleSDF to apply to the creation of a custom dataset for FoundationPose? 

Thank you very much for your response!

**Comment by wenbowen123** [comment]
> Do I necessarily need the pose of the target relative to the camera when creating a custom dataset

If you mean model-free setup, then yes. But you can use bundlesdf to get the mesh directly and run model-based.

**Comment by shirokalu** [comment]
Thank you!!!!

**Comment by shirokalu** [comment]
> > Do I necessarily need the pose of the target relative to the camera when creating a custom dataset
> 
> If you mean model-free setup, then yes. But you can use bundlesdf to get the mesh directly and run model-based.

Additionally, I have one more question: is the 3D reconstruction performance of BundleSDF superior to the model-free setup of FoundationPose? Thank you very much for your prompt response.

**Comment by wenbowen123** [comment]
It depends on the pose quality. If you have the same num of images and same quality of poses, they will be the same. But BundleSDF computes poses automatically for you, which makes things easier.

**Comment by shirokalu** [comment]
thank you!!!!!
