### ISSUE TITLE
Guide custom novel object

### ISSUE THREAD

**Issue by ronnypollak** [NVlabs/FoundationPose#156]
Hello, I have already been looking at some other issues but couldn't quite figure it out fully yet as I am still a beginner in this field.
Could someone provide me with a guide on the following situation:

I have an object that I can take reference videos and pictures of.
What can I do step by step to create a valid dataset and use this dataset with the model?

I currently do not own a depth camera.
I am very grateful for every advice and guidance! Thank you!

**Comment by ronnypollak** [comment]
To add to that. I could use a Kinect to take RGBD reference videos and pictures. Did I understand it correctly that the way would be to use BundleSDF to create a model to then use with FoundationPose?

**Comment by wenbowen123** [comment]
> To add to that. I could use a Kinect to take RGBD reference videos and pictures. Did I understand it correctly that the way would be to use BundleSDF to create a model to then use with FoundationPose?

Yes, this is the easiest way to do.
