### ISSUE TITLE
Poor Quality Mesh Reconstruction from Synthetic Data in run_nerf.py

### ISSUE THREAD

**Issue by LukasBergs** [NVlabs/FoundationPose#157]
Hello all,

Firstly, I want to express my appreciation for the fantastic work @wenbowen123 has done on the project.

My aim is to utilize bundlesdf/run_nerf.py to generate a textured obj file. This generated mesh file will be employed for foundationpose inference.

I've implemented a synthetic data generation pipeline using Nvidia Isaac Sim. This pipeline generates rgb, depth, mask, and cam_in_obj.txt files, following the format of the demo data. Additionally, it generates the intrinsic camera matrix of the simulated camera. 

Upon executing run_nerf.py, I encountered no errors with both the demo data and my synthetic dataset. However, while the reconstructed mesh from the demo data appears satisfactory, the mesh reconstructed from my synthetic data exhibits poor quality.

You can download the generated synthetic data as well as the output from nerf [here](https://drive.google.com/file/d/1dMhJ2shfcpuKNMMnvA5TGyYsLB7g1WvY/view?usp=sharing).

Output from run_nerf.py:
![Screenshot from 2024-06-10 13-11-29](https://github.com/NVlabs/FoundationPose/assets/56199842/f5bcb52e-1e94-4d53-a734-58f5009552fd)
![Screenshot from 2024-06-10 13-02-35](https://github.com/NVlabs/FoundationPose/assets/56199842/34eff616-0e5e-4763-8bd1-e5aa1178290f)

I kindly ask for assistance in troubleshooting this issue. Any insights or guidance on potential causes for the disparity in mesh quality between the demo and synthetic datasets would be greatly appreciated.

Thank you!

Best regards
Lukas

**Comment by wenbowen123** [comment]
Hi, your poses seem wrong. Take a look at `naive_fusion.ply` under the nerf/ folder. It looks messy.

**Comment by LukasBergs** [comment]
Thank you for your reply. 

Is this the convention for the camera coordinate system? 
![image](https://github.com/NVlabs/FoundationPose/assets/56199842/a8de1e13-e53a-4b1c-a3f7-7a6d0099729f)

**Comment by Sgt-Hashtag** [comment]
@wenbowen123 I'm also having this issue with Isaac sim

**Comment by wenbowen123** [comment]
@LukasBergs @Sgt-Hashtag yes the convention is correct.

**Comment by wenbowen123** [comment]
you can refer to the model-free setup in LINEMOD on the data format.
