### ISSUE TITLE
Data requirement for testing model-based pose-estimation

### ISSUE THREAD

**Issue by Muhammadjunaidmalik1** [NVlabs/FoundationPose#159]
Hi ! 

I am trying to test foundation pose algorithm using my own data. Currently, I am using run_demo.py file for pose estimation. I have : 

1. CAD model of the object (.obj file)
2. RGB .png image
3. Depth image

During implementation its asking also for mask for the object. I wanted to ask if I need the segmentation mask for all the images like in test images or do i need just one image initially to register the object like in the mustard0 folder in demo data?

Looking forward for your response.

Best regards,
Muhammad

**Comment by wenbowen123** [comment]
you only need the mask for the first image. 2D bounding box also works.

**Comment by TPF0628** [comment]
> Hi !
> 
> I am trying to test foundation pose algorithm using my own data. Currently, I am using run_demo.py file for pose estimation. I have :
> 
> 1. CAD model of the object (.obj file)
> 2. RGB .png image
> 3. Depth image
> 
> During implementation its asking also for mask for the object. I wanted to ask if I need the segmentation mask for all the images like in test images or do i need just one image initially to register the object like in the mustard0 folder in demo data?
> 
> Looking forward for your response.
> 
> Best regards, Muhammad

Hello, I also want to run the run_demo.py file similar to your operation. However, I am not sure how to obtain the .obj files for the CAD models. I currently have an Intel RealSense D455. Could you please advise me on how to create data in a format similar to the demo data? Thank you.

**Comment by wenbowen123** [comment]
@TPF0628  you can use [BundleSDF](https://github.com/NVlabs/BundleSDF) to create the model.
