### ISSUE TITLE
pose VS center_pose

### ISSUE THREAD

**Issue by zhujingsong** [NVlabs/FoundationPose#16]
Hi, I'm new to 6d pose estimation. 
I noticed that there are two variables-- pose and center_pose in run_demo.py. I guess pose is only the transformation between camera coordinate and mesh model coordinate, while center_pose is the actual transformation between camera coordinate and the standard object coordinate ( O in the centroid of object ). Is that correct?
So, from my understanding, shouldn't we save center_pose for robotic manipulation?

**Comment by wenbowen123** [comment]
you should use the pose since that's the correct one transforming your CAD model. `center_pose` is for viz only.
