### ISSUE TITLE
Run model-free few-shot version error on ycbv dataset —— lack of keyframe.txt

### ISSUE THREAD

**Issue by cheny110** [NVlabs/FoundationPose#161]
Hi,
I follow the instruction to run model-free few-shot version on ycbv dataset. I download BOP version dataset from https://bop.felk.cvut.cz/datasets/ as suggested. The exception occured as follows:

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/home/skysys/Projects/datasets/ycb-video/test/000048/../../keyframe.txt'
  File "/home/skysys/Projects/FoundationPose/datareader.py", line 451, in __init__
    with open(f'{self.base_dir}/../../keyframe.txt','r') as ff:
  File "/home/skysys/Projects/FoundationPose/run_ycb_video.py", line 91, in run_pose_estimation
    reader_tmp = YcbVideoReader(video_dirs[0])
  File "/home/skysys/Projects/FoundationPose/run_ycb_video.py", line 149, in <module>
    run_pose_estimation()
FileNotFoundError: [Errno 2] No such file or directory: '/home/skysys/Projects/datasets/ycb-video/test/000048/../../keyframe.txt'

The dataset directory structure is displayed as below:
ycb-video/
├── camera_cmu.json
├── camera_uw.json
├── dataset_info.md
├── models
├── models_eval
├── models_fine
├── test
├── test_targets_bop19.json
├── train_pbr
├── ycbv_base.zip
├── ycbv_models.zip
├── ycbv_test_bop19.zip
└── ycbv_train_pbr.zip
where can I fetch "keyframe.txt" file ? Sincere thanks.

**Comment by wenbowen123** [comment]
The keyframe.txt file is included if you download from the original paper https://rse-lab.cs.washington.edu/projects/posecnn/
They use this to select a number of frames for benchmarking. However, you can also run every frame and ignore this.

**Comment by cheny110** [comment]
> The keyframe.txt file is included if you download from the original paper https://rse-lab.cs.washington.edu/projects/posecnn/ They use this to select a number of frames for benchmarking. However, you can also run every frame and ignore this.

Sincerely thank you for your reply， the problem has been solved. 

Best regards !
