### ISSUE TITLE
Regarding model-free related files

### ISSUE THREAD

**Issue by dengyufuqin** [NVlabs/FoundationPose#167]
First of all, thank you for your contribution and sharing.

I have a question. In the method in model-free, I have a few questions I would like to ask.
1. What data should be in cam_in_ob?
2. What data is in depth_enhanced?
3. What is the meaning of select_frames.yml?

Thank you very much

**Comment by wenbowen123** [comment]
1)camera pose wrt. object
2)it's just depth image
3)You dont need this for your custom data. This was used to sample few-shot frames on the public benchmark.

**Comment by 8866lt** [comment]
Thank you for your contribution and sharing！！！

I hope this message finds you well. I am currently working on a project involving 6D pose estimation and tracking of novel objects and am highly interested in your FoundationPose framework. 

Could you please provide detailed guidance on how to create and train a custom dataset in a model-free setting using FoundationPose? Specifically, I am looking for information on:

1. How to Prepar and structure the dataset.
2. Required annotations and formats.
3. Training pipeline and key parameters to adjust.

Thank you for your time and assistance. I look forward to your response.
