### ISSUE TITLE
Running FoundationPose on a computing board.

### ISSUE THREAD

**Issue by nirajkark07** [NVlabs/FoundationPose#169]
Hi! 

A bit of a silly question. I am looking to run FoundationPose on a computing board (e.g., orin, nano, etc.). I am not sure which specifications I should be looking for when selecting an appropriate board. Ideally, I would like to run FoundationPose at a minimum of 30 fps. Do you have any reccomendations as to which board I should select to be able to run this algorithim? 

Thank you!

**Comment by ysdagar** [comment]
I am also looking for something for something same. Any suggestion for hardware?

My default go to device would probably Jetson Orin AGX.  I am also looking for a way to eliminate/reduce rasterization from the code somehow (it might sound silly though) as it is most time consuming part.
Can you share any pointers please @wenbowen123 ?

**Comment by wenbowen123** [comment]
@ysdagar @nirajkark07 Orin is preferred. You should be able to get ~100FPS for tracking. Also Thor board will come soon, which is even more powerful. For the ROS version of FoundationPose and deployment on those boards, you can check https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation

**Comment by yashwant-ies** [comment]
Thank you so much @wenbowen123 ! Will Thor board be targeted for embedded AI market and is next generation of Orin?

**Comment by wenbowen123** [comment]
@yashwant-ies I'm not the best person to answer this. You can check more [here](https://nvidianews.nvidia.com/news/nvidia-unveils-drive-thor-centralized-car-computer-unifying-cluster-infotainment-automated-driving-and-parking-in-a-single-cost-saving-system). You can also create product related issues in the isaac ros repo I posted above.

**Comment by nirajkark07** [comment]
Thank you so much @wenbowen123. I will be marking this issue as closed.
