### ISSUE TITLE
model-free pipeline question

### ISSUE THREAD

**Issue by zhujingsong** [NVlabs/FoundationPose#17]
To reconstruct the mesh, I need some information about reference images, like rgbds, depths, masks and cam_in_obs.
Could you show how to generate the 'cam_in_obs' files?

**Comment by wenbowen123** [comment]
For example, you can use the full pipeline of [BundleSDF](https://github.com/NVlabs/BundleSDF), or other SLAM methods, or forward kinematics if you have a calibrated arm.
