### ISSUE TITLE
'YcbVideoReader' object has no attribute 'keyframe_lines'

### ISSUE THREAD

**Issue by QQH00** [NVlabs/FoundationPose#170]
YcbVideoReader only read keyframe.txt when BOP not in self.base_dir. But when run_pose_estimation(line114 of run_ycb_video.py) it would check if not reader.is_keyframe(i) no matter the dataset is BOP or not.

**Comment by QQH00** [comment]
I commented out the code that checks if it is a keyframe. And the run_ycb_video can run well.

**Comment by wenbowen123** [comment]
this is only needed on the original YCB-Video benchmark (from Pose-CNN). On BOP you can comment it.
