### ISSUE TITLE
Real-time estimation issue where the object diverges when it goes out of bounds

### ISSUE THREAD

**Issue by SeungHunJeon** [NVlabs/FoundationPose#176]
Hi, thank you for sharing your great works ! 

I attempted to perform real-time pose estimation using RGBD sensor data from the D435. 

However, I encountered an issue where the object diverges and does not re-converge once it goes out of the scene.

How can this problem be resolved?

https://github.com/NVlabs/FoundationPose/assets/54147180/c792f60c-cd1a-463b-877b-6f43bd902f88

**Comment by Kaivalya192** [comment]
> Hi, thank you for sharing your great works !
> 
> I attempted to perform real-time pose estimation using RGBD sensor data from the D435.
> 
> However, I encountered an issue where the object diverges and does not re-converge once it goes out of the scene.
> 
> How can this problem be resolved?
> 
>  IMG_9041.online-video-cutter.com.mp4

hey there,
i think you are using the existing logic of this repo that registers pose for the first frame and then for next all frame it estimates pose.

when it is out of camera send the pose to score network and see the score. Then set some threshold accordingly. if threshould is crossed then reregister the pose and pass the mask for that.

as mentoined in #136

**Comment by SeungHunJeon** [comment]
Ok then, I need to stop the tracking and re-estimate the pose accordingly. I think to resolve that issue in real-time, masking should be processed automatically, not manually.

**Comment by assia855** [comment]
how can I do that please @Kaivalya192 ?

**Comment by monajalal** [comment]
@SeungHunJeon Great job!

Could you please share the code snippet where you read the data from your camera? I have the same exact camera and could use some help.
