### ISSUE TITLE
Something wrong happened while seting up mycuda.

### ISSUE THREAD

**Issue by warriorhcs** [NVlabs/FoundationPose#178]
![IMG_20240707_190846495](https://github.com/NVlabs/FoundationPose/assets/121141205/dc3d697e-93cc-48ba-ba19-43f8e6419325)
When I execute the final step of conda setup using build_all_bash.sh, the command python -m pip install -e . results in the error above. Could you please help me understand what is causing this? Thank you for your assistance."

ps: The related code in build_all_bash.sh is：
# Install mycuda
cd ${PROJ_ROOT}/bundlesdf/mycuda && \
rm -rf build *egg* *.so && \
python -m pip install -e .

**Comment by icleen** [comment]
I have the same issue

**Comment by Ashima1012** [comment]
I have the same issue

**Comment by wenbowen123** [comment]
can you paste here the full log?

**Comment by icleen** [comment]
So I was able to resolve it using the following steps:
CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11:$CONDA_PREFIX/include/eigen3
add the line "~/.miniconda3/envs/foundationpose/include/eigen3" to bundlesdf/mycuda/setup.py::38 so it can find Eigen.

The CMAKE_PREFIX_PATH gets overwritten so you completely lose the correct eigen path. Add the line above and changing the prefix path and then just running bash build_all_conda.sh seems to work for me.

**Comment by gemcollector** [comment]
I have the same issue. 
The above solution seems not work for me.

**Comment by wenbowen123** [comment]
glad it works!
