### ISSUE TITLE
could not load weights

### ISSUE THREAD

**Issue by puyilin** [NVlabs/FoundationPose#180]
hello engineer. i have downloaded the folder 2024-01-11-20-02-45 and put it in weights. when i run run_demo.py, a traceback occur:
![2024-07-09 16-40-12屏幕截图](https://github.com/NVlabs/FoundationPose/assets/103842176/ea55784f-35fc-4185-9d17-5047b5f5b52e)
the key can't match

**Comment by TianxingChen** [comment]
I am meeting the same problem.

**Comment by wenbowen123** [comment]
For the refiner, you should use `2023-10-28-18-33-37`
For scorer, you should use `2024-01-11-20-02-45`
