### ISSUE TITLE
Use FoundationPose in Game Engines

### ISSUE THREAD

**Issue by rayraurray** [NVlabs/FoundationPose#183]
How can I export the model to be used in a game engine like Unity or Unreal? Which files should be exported and what file format should they be in?

**Comment by wenbowen123** [comment]
> export the model to be used in a game engine

can you explain what this means?

**Comment by rayraurray** [comment]
Can the model be ran in a Game Engine environment like Unity Engine? If not then can an .onnx file be retrieved?

**Comment by wenbowen123** [comment]
I dont think there is anything preventing it from running in a game engine. It's even easier than in real-world, as you already have some information handy like RGBD, 3D models.
