### ISSUE TITLE
Run_demo.py not working

### ISSUE THREAD

**Issue by phsilvarepo** [NVlabs/FoundationPose#184]
Hello there, 
I was able to perform the initial setup as indicated, When running the demo script inside of the docker container the error occured: ```AttributeError:**` 'NoneType' object has no attribute 'cluster_poses'```
I will put the complete output here but the remaining steps worked. As for the build of bash build_all.sh inside the container also gave no errors or warnings.

![Screenshot from 2024-07-12 10-19-31(1)(1)](https://github.com/user-attachments/assets/388f195e-9264-403c-bb0f-718c0ed849e5)
![Screenshot from 2024-07-12 10-19-21](https://github.com/user-attachments/assets/0584a545-1679-4383-9d80-151a105bbad9)
![Screenshot from 2024-07-12 10-19-04](https://github.com/user-attachments/assets/6dd4fbf9-c11e-48ed-bf99-da3358291bb0)

Any feedback would be great, thanks in advance.

**Comment by tathya7** [comment]
@phsilvarepo How did you solve this

**Comment by phsilvarepo** [comment]
Hello @tathya7,
I just followed the instructions from this other [issue](https://github.com/NVlabs/FoundationPose/issues/89). Let me know if you were able to fix it,
