### ISSUE TITLE
How does FoundationPose pick the first frame for the pose estimate?

### ISSUE THREAD

**Issue by sharanyashastry** [NVlabs/FoundationPose#186]
Hi! This is some great work @wenbowen123! It's turning out to be very useful for my research. 

I was wondering how the initial frame is estimated/placed? I was able to get it to run for a novel object using the model based method. I just want my initial frame to be rotated by 45 degrees in order to have it align in a more visually intuitive way with the object I'm tracking. 

For example, what if I wanted this initial triad to be rotated in such a way that the blue axis aligns with the text and the red points at the cap but the green axis is not visible?
![image](https://github.com/user-attachments/assets/5f070ac7-0b28-4d0f-847c-31c0a8d99e36)

**Comment by anish-bhattacharya** [comment]
wow this is an amazing question i also want to know this very important piece of information!!!!!11!1!!!!

**Comment by wenbowen123** [comment]
you can change it in the mesh. For the OBJ file, you can open it in Meshlab and rotate it to the way you want, then over-write the original one.

**Comment by sharanyashastry** [comment]
Could you point me to where in the code the initialization is done?

**Comment by wenbowen123** [comment]
there is no code needed for this. As I said, you just open the OBJ file in Meshlab and rotate it to the way you want, then over-write the original one.

**Comment by sharanyashastry** [comment]
Here's what my obj file looks like which is axis aligned and oriented the way I want.
![image](https://github.com/user-attachments/assets/8d2cc742-c689-4693-a565-1a8265fbecf8)

Here's what the tracking looks like:
![image](https://github.com/user-attachments/assets/3804ff7e-584e-4a75-96f2-d79fea609d37)

I would expect that this should have foundation pose pick an axis aligned initial pose. I'm not sure why this isn't the case - do you have any suggestions?

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L69
what if you change this line to 
```
center_pose = pose
```

**Comment by sharanyashastry** [comment]
I made the change and this is what happens (images from two runs with the same initial pose):
![image](https://github.com/user-attachments/assets/5421ca90-d449-4284-b022-60d4a4e95b17)
![image](https://github.com/user-attachments/assets/caa0c88c-3e6d-4735-b1db-637184d00f7b)

From different initial pose:
![image](https://github.com/user-attachments/assets/c89373fe-bafe-40a2-82ab-1be7386ebadc)

**Comment by wenbowen123** [comment]
It seems like they are axis-aligned now? It's hard to tell from your mesh editing tool how the object is oriented.

**Comment by sharanyashastry** [comment]
It isn't consistent. It sometimes picks the initial pose to be axis aligned but not always. If you look at the first two images, blue and green axes are wrong.

**Comment by wenbowen123** [comment]
Are you able to share your data? I can take a closer look at it.

**Comment by abhishekmonogram** [comment]
@sharanyashastry @wenbowen123 have you been able to find a resolution to this problem? I made the change that @wenbowen123 suggested but still the problem persists in some cases. I also have been experiencing something similar where the coordinate frame is sometimes flipped.

**Comment by mathanprasannakumar** [comment]
@wenbowen123  , I am also getting the same issue as @sharanyashastry  mentioned , initial pose estimate axis convention are not consistant across multiple rerun , Could you suggest any way to solve this ?
