### ISSUE TITLE
Multithreading and multiprocessing issues

### ISSUE THREAD

**Issue by GitMichaelR** [NVlabs/FoundationPose#187]
Hello, 

I run two threads with one foundationpose model each.  However when they are both executing the register function and within it the erode depth or bilateral_filter_depth function, an error occurs because of warp. So currently, as  a "fix", I am running the register function wit a gpu_lock which is basically as fast as not using multithreading. Is there a workaround?

Thank you!

**Comment by GitMichaelR** [comment]
And with mutliprocessing I get a pickling error like: 
".../multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
 File "stringsource", line 2, in zmq.backend.cython.context.Context.__reduce_cython__"

**Comment by GitMichaelR** [comment]
And with multiprocessing I get an error like: 
".../multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "stringsource", line 2, in zmq.backend.cython.context.Context.__reduce_cython__

**Comment by wenbowen123** [comment]
what if you set the start method to "spawn"?

**Comment by GitMichaelR** [comment]
Like I said in the comment before, I get the error: 

".../multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
File "stringsource", line 2, in zmq.backend.cython.context.Context.reduce_cython

Can you by any chance provide a working minimal multithreaded example?
