### ISSUE TITLE
the definition of the coordinate

### ISSUE THREAD

**Issue by sgg-al** [NVlabs/FoundationPose#188]
How is the pose coordinate system of the detected object defined? Is it the default coordinate system in the OBJ model?

**Comment by sharanyashastry** [comment]
I opened this issue a couple days ago with the same question - https://github.com/NVlabs/FoundationPose/issues/186

From reading the paper, it seemed like it's probably not trying to track the frame in the obj file. It says it's some sampling based algorithm for the initial pose followed by some scoring algorithm to find the most likely one. However, it's always consistent on my example and theirs so I'm not sure if that's really the case.

**Comment by wenbowen123** [comment]
> Is it the default coordinate system in the OBJ model?

yes, this is true.
