### ISSUE TITLE
Question about pre steps before train NeRF

### ISSUE THREAD

**Issue by QQH00** [NVlabs/FoundationPose#191]
To train NeRF in a model-free mode, the depth map from the ref_view is first converted into a point cloud. Then, using cam to world, the point cloud is transformed from the camera coordinate system to the world coordinate system. Finally, the point clouds from several images are combined to obtain the initial point cloud of the object.

I am confused about why the sampled data in ref_view comes from the same object under multiple scenes with different positions and orientations. Why can the point clouds reconstructed from these depth maps be combined to form a complete point cloud of the object?

**Comment by wenbowen123** [comment]
> why the sampled data in ref_view comes from the same object under multiple scenes with different positions and orientations.

this is just because of how the public dataset is provided. There are limited view diversity in each scene. For one's own application, you can capture from different angles in the same scene.
