### ISSUE TITLE
qt.qpa.xcb: could not connect to display 

### ISSUE THREAD

**Issue by Raviteja-T** [NVlabs/FoundationPose#192]
Hi, I am using Docker. 

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/conda/envs/my/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)

**Comment by carynbear** [comment]
Are you running this locally or over ssh?

**Comment by Raviteja-T** [comment]
@carynbear 
Thanks you. Its working. 
![github](https://github.com/user-attachments/assets/cb830a57-9532-4158-8ed5-d820074b67ea)

**Comment by Raviteja-T** [comment]
Hi @carynbear 

Now I am going to test with my own datasets recorded by a RealSense camera D435i. My image folder structure is as shown in the image below. My question is, how can I generate a mesh image of my object?

![real](https://github.com/user-attachments/assets/d79f7819-6fe4-4023-baa0-0e2d92322c06)

Request : Kindly provide me with instructions on how to process my own datasets for this procedure. If there are any available video or PDF files, please share them with us.

**Comment by wenbowen123** [comment]
glad it's working now!

**Comment by mesilver1218** [comment]
```c++
docker run -it --rm --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix foundationpose
``` 

In my case, running the Docker container in a different way solved the issue.
