### ISSUE TITLE
 texture files（.mtl，.png）necessary for model -based FP ?

### ISSUE THREAD

**Issue by landian233** [NVlabs/FoundationPose#193]
Thanks for your excellent job!
 I'm trying to integrate FP with realsense camera, using model-based mode to estimate pose of some components with their .obj.
Are those texture files（.mtl，.png）necessary for model -based FP ? When I'm reading the code, I didn’t find anything to invoke those files in the 'mesh' filefolder.

I kindly ask for assistance in troubleshooting this issue.THANK YOU!

**Comment by wenbowen123** [comment]
if you dont have the texture files, it might still work. But having that will greatly improve the results. If your object is just pure-colored, you can add a color using this [function](https://github.com/NVlabs/FoundationPose/blob/main/Utils.py#L658).

**Comment by landian233** [comment]
I noticed that FP project includes nerf_runner.py and run_nerf.py. may I ask What difference between those .py and your Bundlesdf project .Thank you very much for your answer！

**Comment by landian233** [comment]
THANK YOU! it helps a lot

**Comment by prrw** [comment]
It also works if you use STL file instead of OBJ and then you dont need Texture or Material. However, I am not impressed by the accuracy.
