### ISSUE TITLE
Hello, I would like to ask about a 4x4 pose matrix. Does it refer to the transformation from the coordinate system of an STL or OBJ file to the camera coordinate system?

### ISSUE THREAD

**Issue by wsq1010** [NVlabs/FoundationPose#196]

**Comment by wsq1010** [comment]
The translation part T in the matrix, is it a translation relative to the camera principal point?

**Comment by buduz** [comment]
I have the same problem, the pose I get is obviously not based on the camera coordinate system, but the image drawn under debug is very similar, and now I am confused

**Comment by buduz** [comment]
yes

**Comment by wenbowen123** [comment]
yes, and the translation is from the STL/OBJ origin to the camera center.
