### ISSUE TITLE
Can the algorithm achieve sub-millimeter absolute positional accuracy?Does the accuracy of the algorithm depend on the accuracy of the camera, or can the algorithm improve the accuracy of the camera?

### ISSUE THREAD

**Issue by sgg-al** [NVlabs/FoundationPose#198]
What is the absolute accuracy of the pose obtained by this algorithm? Has the author team done any relevant work to verify it?

**Comment by Cheney-36** [comment]
顺便一问，这项工作将会在什么时候被集成进issac lab

**Comment by Cheney-36** [comment]
By the way, when will this work be integrated into the ISSAC lab

**Comment by wenbowen123** [comment]
@Cheney-36 it has been integrated into Isaac ROS. See our readme.

**Comment by Cheney-36** [comment]
> @Cheney-36它已集成到 Isaac ROS 中。请参阅我们的自述文件。

I didn't express myself clearly. I am very curious about your AutoMate work, which is excellent. I saw plans to integrate it into Isaac Lab. Do you know the timeline?

**Comment by wenbowen123** [comment]
@Cheney-36 it has been released [here](https://github.com/isaac-sim/IsaacGymEnvs/blob/automate/docs/automate.md).

**Comment by Cheney-36** [comment]
Thank you for your reminder, excellent work
