### ISSUE TITLE
Can you release the supplementary materials?

### ISSUE THREAD

**Issue by shanice-l** [NVlabs/FoundationPose#2]
Hi, Bowen

Great work! It definitely would be a breakthrough in object pose estimation.

Can you release the supplementary materials in arXiv or your project page? I'd like to know more details about your work.

**Comment by shanice-l** [comment]
For example, I'm curious about the detection/segmentation method for pose initialization.

**Comment by Eddieeee-Liu** [comment]
+1

**Comment by NotEnterprising** [comment]
+1

**Comment by Charles23R** [comment]
+1

**Comment by wenbowen123** [comment]
Hi, we are planning to release everything in March.
