### ISSUE TITLE
docker build and conda build error 

### ISSUE THREAD

**Issue by ZijianWu1121** [NVlabs/FoundationPose#200]
when i use the command 
`CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh`

it shows the errors below:

and I use RTX3090 with CUDA11.8 in ubuntu20.04

        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
        
        /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code

**Comment by csjiyw** [comment]
same

**Comment by csjiyw** [comment]
> when i use the command `CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh`
> 
> it shows the errors below:
> 
> and I use RTX3090 with CUDA11.8 in ubuntu20.04
> 
> ```
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(214): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant() const") from a __device__ function("calculateBarycentricCoordinate2DKernel") is not allowed
>     
>     /home/ubuntu/hand/foundationpose/FoundationPose-main/bundlesdf/mycuda/common.cu(216): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)2, (int)2, (int)0, (int)2, (int)2> > ::determinant const" is undefined in device code
> ```

how you fixed?

**Comment by soom1017** [comment]
@csjiyw Hello, I'm suffering with the same problem. Any progress?

**Comment by shewangmu** [comment]
did you fix the error? I meet the same problem

**Comment by soom1017** [comment]
> did you fix the error? I meet the same problem

I resolved this issue by modifying the first line of Dockerfile to use CUDA 11.8 instead of 11.3 and then rebuilding the image. Please give it a try:)

**Comment by SiruiXie** [comment]
> > did you fix the error? I meet the same problem
> 
> I resolved this issue by modifying the first line of Dockerfile to use CUDA 11.8 instead of 11.3 and then rebuilding the image. Please give it a try:)

Thanks for your advise! However, instead of developing with docker, I am using conda. And I have written in my ~/.bashrc file to set the compiler to be CUDA-11.8, I still got the same errors. Got any idea why this is happening? @soom1017

**Comment by LiNO3Dy** [comment]
change to calculating without denominator.determinant()


__device__ void calculateBarycentricCoordinate2DKernel(const Eigen::Matrix<float,3,2> &triangle, const Eigen::Vector2f &p, Eigen::Vector3f &w)
{
    Eigen::Vector2f CA = triangle.row(0)-triangle.row(2);
    Eigen::Vector2f AC = -CA;
    Eigen::Vector2f CP = p-triangle.row(2).transpose();
    Eigen::Vector2f AB = triangle.row(1)-triangle.row(0);
    Eigen::Vector2f AP = p-triangle.row(0).transpose();

    float denominator_det = AB(0) * AC(1) - AB(1) * AC(0);

    float numerator1_det = CA(0) * CP(1) - CA(1) * CP(0);
    w(1) = numerator1_det / denominator_det;

    float numerator2_det = AB(0) * AP(1) - AB(1) * AP(0);
    w(2) = numerator2_det / denominator_det;

    w(0) = 1 - w(1) - w(2);
}
