### ISSUE TITLE
Memory issues with computing cropped batch point clouds in Pose Selection (Scoring)

### ISSUE THREAD

**Issue by carynbear** [NVlabs/FoundationPose#202]
Any reason why there is a difference between how cropped point clouds (`xyz_mapBs`) is computed for Pose Refinement vs Pose Scoring? 

In Pose Refinement, the code goes from `depth` --> `xyz_map` --> expanded and cropped `xyz_mapBs` .  **No memory issues.**

In Pose Scoring, you go from `depth` --> expanded and cropped `depthBs` --> expanded and cropped `xyz_mapBs`. **Memory issues.**

**Comment by carynbear** [comment]
Pose Refinement Code Trace:
1. `xyz_map` is computed from `depth` in `FoundationPose.register` and passed into `refiner.predict` [estimater.py#L214-L215](https://github.com/NVlabs/FoundationPose/blob/main/estimater.py#L214-L215)
2. `xyz_map` is passed to `make_crop_data_batch` [predict_pose_refine.py#L184](https://github.com/NVlabs/FoundationPose/blob/main/learning/training/predict_pose_refine.py#L184) and [predict_pose_refine.py#L26](https://github.com/NVlabs/FoundationPose/blob/main/learning/training/predict_pose_refine.py#L26)
3. `xyz_map` is expanded by batches and cropped [predict_pose_refine.py#L72](https://github.com/NVlabs/FoundationPose/blob/main/learning/training/predict_pose_refine.py#L72)
4. No memory error

**Comment by carynbear** [comment]
Pose Scoring Code Trace:
1. `depth` is passed into `scorer.predict` but **`xyz_map` is NOT passed in** [estimater.py#L219](https://github.com/NVlabs/FoundationPose/blob/main/estimater.py#L219) 
2. `depth` is expanded by batched and cropped in `depthBs` [predict_score.py#L90](https://github.com/NVlabs/FoundationPose/blob/main/learning/training/predict_score.py#L90)
3. `depthBs` is passed to `dataset.transform_batch` through `BatchPoseData` [predict_score.py#L109-L110](https://github.com/NVlabs/FoundationPose/blob/main/learning/training/predict_score.py#L109-L110)
4. `xyz_mapBs` is computed from `depthBs` in [h5_dataset.py#L158-L164](https://github.com/NVlabs/FoundationPose/blob/main/learning/datasets/h5_dataset.py#L158-L164) causing a memory error.

**Comment by wenbowen123** [comment]
Hi, good catch. Both ways work and they are actually identical.

**Comment by carynbear** [comment]
@wenbowen123 will make a pull request and send it your way soon!
