### ISSUE TITLE
Issues with running FoundationPose in parallel

### ISSUE THREAD

**Issue by shivanshpatel35** [NVlabs/FoundationPose#203]
I am trying to integrate multi-object tracking using the FoundationPose (FP) codebase. For this, I am running FoundationPose in multiple threads and printing the pose of the objects in a while loop. The code prints the correct pose for some time (~10 seconds) but then continues printing the same pose even if I move the object. I ensured that no data is read simultaneously, hence I probably don't have race conditions. Here is the minimal code to explain the code structure:

```
class FoundationPoseWrapper:
    def __init__(self, object_data):
        self.fp = FoundationPose(object_data)
    
    def get_pose(self):
        pose = get_pose_fp()
        return pose

class MultiFoundationPose:
    def __init__(self):
        camera_readers = get_camera_readers() # Using different camera for each object to ensure no issues from cameras
        self.threads = []
        self.lock = threading.lock()
        objects_data = get_objects_data()
        for object_data, reader in enumerate(objects_data):
            self.threads.append(threading.Thread(target=self.track, args=(object_data, reader))
            self.threads[-1].start()
        
    def track(self, object_data, reader):
        fp = FoundationPoseWrapper()
        while True:
            pose = fp.get_pose()
            with self.lock:
                self.results[obj_name] = pose

    def get_results(self):
        with self.lock:
            results = self.results.copy()
        return results


multi_tracker = MultiFoundationPose()
while True:
        print(multi_tracker.get_results())
```

My observations are as follows:
1. The pose is printed correctly for some time but then stops updating.
2. When running the code in the debugger, it gets stuck inside the FoundationPose code, often at this [line](https://github.com/NVlabs/FoundationPose/blob/main/learning/training/predict_pose_refine.py#L236). Running the same line in the debug console returns `Unable to find thread for evaluation`. Regular solutions from internet regarding this error don't help.

Can someone please help me with this?

**Comment by wenbowen123** [comment]
1. did you monitor the GPU memory and make sure it's never OOM?
2. did you check in each thread, the camera images are constantly being fed correct (no interruption after a while)?

**Comment by GitMichaelR** [comment]
@shivanshpatel35 Did you have to change something in the codebase to make multithreading work? Since, for me, when the register function gets called in multiple threads, I get an error with the warp library that is used. 
Can you by any chance provide more of your code ?

**Comment by shivanshpatel35** [comment]
@wenbowen123 1. GPU is never OOM
2. Most probably there is no interruption. I can see that the camera feed is running, just until the code stops -- hence my conclusion. After this, I cannot check for feed within the code as I get `Unable to find thread for evaluation`.

**Comment by shivanshpatel35** [comment]
@GitMichaelR What error do you get? You can email me on shivanshpatel35@gmail.com and I can share you my _not-so-organized_ code there.

**Comment by wenbowen123** [comment]
while there maybe a way to make it work with native python multi-threading/processing, another simpler option might be launching multiple ROS nodes for communication, if you use ROS.

**Comment by shivanshpatel35** [comment]
Thanks for the suggestion. I will give it a try.

**Comment by ammar-n-abbas** [comment]
We have implemented multi-object tracking in this repo:

https://github.com/ammar-n-abbas/FoundationPoseROS2
