### ISSUE TITLE
I'm getting errors for "build_all[dot]sh" and "run_demo[dot]py" with ubuntu 22 in wsl 2 on windows 10. Please point me in the right direction.

### ISSUE THREAD

**Issue by ahiyantra** [NVlabs/FoundationPose#208]
I was unable to make the officially prepared docker image run on my device, so i followed the recommended steps to prepare my own docker image but i still continue to get errors. The output for "nvidia-smi" is included near the end of the copy-pasted terminal messages for reference, which are linked as a github gist. Please help me figure out how i can solve these problems.

[github gist with terminal messages](https://gist.github.com/ahiyantra/00a0917441394873c998f23a50307dc7)

**Comment by ahiyantra** [comment]
I face an error with "nvdiffrast" that was resolved by building it separately but an error with "nonetype" and "mycpp" followed that.

**Comment by ahiyantra** [comment]
I was able to make the first python demo script run without errors by executing the same bash commands as my previous attempt in a slightly different order with some repetition (solution for nonetype/mycpp issue with "build_all_conda[dot]sh", followed by solution for the nvdiffrast issue, followed by solution for the nonetype/mycpp issue with "build_all[dot]sh") after setting the values for the NINJA_JOBS & MAKEFLAGS system variables to "1" & "-j1" respectively. The second python demo script still seems to have an error. It stops suddenly with a tensor/array of numbers with decimals.

**Comment by ahiyantra** [comment]
I found a solution after analyzing the code. The "cv2.waitKey()" function waits for a key press for a specified amount of time in milliseconds. In the second python demo script, a duration of 1 millisecond is specified for it. If a key isn't pressed within this time, the function continues execution & as a duration of 1 millisecond is a very short, the window closes almost immediately after showing the image. To keep the window open until the user manually closes it, we should replace "1" with "0". The duration of 1 millisecond is typically used for video processing to allow for a smooth display while still being responsive. The duration of 0 millisecond is used like a proxy, allowing a single image to be displayed without the window closing abruptly.

**Comment by ahiyantra** [comment]
It seems that this implementation of this model is meant for detecting only one object at a time in a provided image, so other methods are needed to detect multiple objects in a provided image before the list of detected objects is passed to this implementation of this model in order for them to be processed one at a time. Finally, if a demo script crashes upon running for the first time, then sometimes, it can be made to work by running it again once. Beyond that, there are no more errors now.

**Comment by OxygenIsland** [comment]
> I face an error for "nvdiffrast" that was resolved by shifting to where this library is located & rebuilding it separately but a different error for "nonetype"/"mycpp" followed soon.
Hello @ahiyantra , my experience is exactly the same as yours, I am stuck here:
`RuntimeError: Error building extension 'nvdiffrast_plugin': [1/16] c++ -MMD -MF common.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/my/lib/python3.9/site-packages/torch/include -isystem /opt/conda/envs/my/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/my/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/envs/my/lib/python3.9/site-packages/torch/include/THC -isystem /opt/conda/envs/my/include -isystem /opt/conda/envs/my/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /opt/conda/envs/my/lib/python3.9/site-packages/nvdiffrast/common/common.cpp -o common.o`

Please point me in the right direction.
