### ISSUE TITLE
Dangerous line of code in run_demo.py

### ISSUE THREAD

**Issue by aenoca** [NVlabs/FoundationPose#209]
The line of code `os.system(f'rm -rf {debug_dir}/* && mkdir -p {debug_dir}/track_vis {debug_dir}/ob_in_cam')` in the `run_demo.py` file is potentially very dangerous if for some reason `debug_dir` ends up becoming an empty string. I suggest finding another way of writing this, or adding a safety line.

**Comment by ahiyantra** [comment]
Maybe a null check can be added to avoid resulting errors.

**Comment by wenbowen123** [comment]
Thanks for bringing up this point! This repo was originally intended to run inside a docker. Some users want to run via conda. But it was not extensively tested. You can add a safety check in your fork.
