### ISSUE TITLE
RUNNING LINEMOD DATA : ValueError: primitive vertices are immutable: not setting!

### ISSUE THREAD

**Issue by NicCusinato** [NVlabs/FoundationPose#21]
Running into this error when trying to run linemod. Here is my linemod file setup as well, possibly I don't have the folder setup correctly?
 
 
 File "/mnt/c/foundationpose/estimater.py", line 51, in reset_object
    mesh.vertices = mesh.vertices - self.model_center.reshape(1,3)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/trimesh/primitives.py", line 76, in vertices
    raise ValueError("primitive vertices are immutable: not setting!")
ValueError: primitive vertices are immutable: not setting!
(my) root@docker-desktop:/mnt/c/foundationpose# python run_linemod.py --linemod_dir /mnt/c/DATASETS/LINEMOD --use_reconstructed_mesh 1
Warp 1.0.2 initialized:
   CUDA Toolkit 11.5, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 3060" (12 GiB, sm_86, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.0.2
Module warp.utils load on device 'cuda:0' took 5.22 ms
Module Utils load on device 'cuda:0' took 8.15 ms
Traceback (most recent call last):
  File "run_linemod.py", line 149, in <module>
    run_pose_estimation()
  File "run_linemod.py", line 101, in run_pose_estimation
    est = FoundationPose(model_pts=mesh_tmp.vertices.copy(), model_normals=mesh_tmp.vertex_normals.copy(), symmetry_tfs=None, mesh=mesh_tmp, scorer=None, refiner=None, glctx=glctx, debug_dir=debug_dir, debug=debug)
  File "/mnt/c/foundationpose/estimater.py", line 26, in __init__
    self.reset_object(model_pts, model_normals, symmetry_tfs=symmetry_tfs, mesh=mesh)
  File "/mnt/c/foundationpose/estimater.py", line 51, in reset_object
    mesh.vertices = mesh.vertices - self.model_center.reshape(1,3)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/trimesh/primitives.py", line 76, in vertices
    raise ValueError("primitive vertices are immutable: not setting!")
ValueError: primitive vertices are immutable: not setting!

![Screenshot 2024-04-02 081003](https://github.com/NVlabs/FoundationPose/assets/157613567/43c91338-df19-4c7d-a982-0f290091b1b7)
![Screenshot 2024-04-02 081019](https://github.com/NVlabs/FoundationPose/assets/157613567/93b5bba3-202f-4ed7-a291-8a189e8ed1e4)

**Comment by wenbowen123** [comment]
If you change estimater.py, line 51 to:
`mesh.vertices = mesh.vertices.copy() - self.model_center.reshape(1,3)`
Does it work?

**Comment by NicCusinato** [comment]
> If you change estimater.py, line 51 to: `mesh.vertices = mesh.vertices.copy() - self.model_center.reshape(1,3)` Does it work?

It did not, same error seems to appear

**Comment by wenbowen123** [comment]
@NicCusinato Did you ever try running this with docker?

**Comment by NicCusinato** [comment]
> @NicCusinato Did you ever try running this with docker?

It is being run through the docker container, did not seem to have any issues with the build

**Comment by NicCusinato** [comment]
> @NicCusinato Are you able to print(mesh.vertices)? Is this returning something or is a NoneType object? Also what is the type of that object?

this is what it returns
![image](https://github.com/NVlabs/FoundationPose/assets/157613567/8118184c-d366-4d2e-be6d-6b828ad5dda0)

**Comment by abhishekmonogram** [comment]
> > @NicCusinato Are you able to print(mesh.vertices)? Is this returning something or is a NoneType object? Also what is the type of that object?
> 
> this is what it returns. Seems to just be an array ![image](https://private-user-images.githubusercontent.com/157613567/319159702-8118184c-d366-4d2e-be6d-6b828ad5dda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzQ1NDgsIm5iZiI6MTcxMjE3NDI0OCwicGF0aCI6Ii8xNTc2MTM1NjcvMzE5MTU5NzAyLTgxMTgxODRjLWQzNjYtNGQyZS1iZTZkLTZiODI4YWQ1ZGRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxOTU3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTNkMGM2NzUyZjE1NjhjYzFmZGI4NTRhN2JmNzI5NTgxNzQzYjVlMmRhOTA4YjZkYWJkNWU4MGNlMTNmYjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NmsG8whZMGFQsr7L3PIfl-NjhewDAysp4R8iB22lJQs)

You seem to be using a cube as the object to track. I think what bowen suggested above should work. You could try with any other mesh object like the one provided with demo data to verify the pipeline

**Comment by NicCusinato** [comment]
it returns a class of 'trimesh.primitives.Box.' The print(self.model_center.reshape(1,3)) returns [[0. 0. 0.]] meaning that subtracting line of mesh.vertices - self.model_center.reshape(1,3) is two non-comparable arrays, is that the issue?

**Comment by sabinecelina** [comment]
Got the same error, solved it by creating a new mesh from the old mesh: 
```
new_vertices = mesh.vertices - self.model_center.reshape(1, 3)
mesh = trimesh.Trimesh(vertices=new_vertices, faces=mesh.faces)
```
