### ISSUE TITLE
How to use your own Realsense camera to create an OBJ model for pose estimation?

### ISSUE THREAD

**Issue by Yeager-101** [NVlabs/FoundationPose#216]
God, someone please help me. I have a Realsense D455 camera now. I want to use it to estimate the pose of my own objects in real time. According to Kaivalya192's [suggestions](https://github.com/Kaivalya192/Object_Reconstruction), I have tried to build the environment no less than 6 times these days, but I found that I can't build it correctly at all. Can anyone tell me how to generate an obj model correctly and quickly to estimate the pose of a custom object? Thank you!

**Comment by wenbowen123** [comment]
How does your object look like? For most of objects, you can use our previous work [BundleSDF ](https://github.com/NVlabs/BundleSDF)to build the mesh.

**Comment by Shang-cl** [comment]
> How does your object look like? For most of objects, you can use our previous work [BundleSDF ](https://github.com/NVlabs/BundleSDF)to build the mesh.

Thank you very much for your reply. I am now trying to use BundleSDF to build my target mesh. I am wondering if I need to perform 6D pose estimation on multiple different objects at the same time, how should I build my mesh? Should I build the mesh for each object separately or in other ways?
