### ISSUE TITLE
Convert the dataset to BOP format

### ISSUE THREAD

**Issue by W-QY** [NVlabs/FoundationPose#217]
Thank you for your excellent work! I hope to use your public dataset and try to convert it to BOP format. I found that the rotation_matrix in the state.json file does not meet the definition (matrix is ​​orthogonal and determinant is 1). I would like to ask you how it is defined and how to convert it to pose labels in BOP format and match it with the mesh.

**Comment by wenbowen123** [comment]
> the rotation_matrix in the state.json file

which dataset are you referring?

**Comment by W-QY** [comment]
> > the rotation_matrix in the state.json file
> 
> which dataset are you referring?

Hi, I'm glad to see your reply. I'm talking about objaverse datasets. Later, I found that I needed to perform a scale operation to get the rotation matrix. However, I still don't know how to convert to get the pose of the object relative to the camera, like "cam_r_m2c" and "cam_t_m2c" in the BOP dataset, so that the.glb mesh file can match the pose.

**Comment by W-QY** [comment]
I guess the "transform_matrix_world" in the state.json file is the pose of the object with respect to the world coordinate system, and the calculated "world_in_cam" (set glcam_in_cvcam as in the code) is the pose of the world coordinate system with respect to the camera. However, I obtained the pose by calculating "world_in_cam@transform_matrix_world.T" and rendered the object's.GLB file using pytorch3d. The resulting image did not match the image in the dataset. What's the problem, please?

**Comment by wenbowen123** [comment]
```
with open(f'{base_dir}/camera_params_000000.json','r') as ff:
      camera_params = json.load(ff)
with open(f'{base_dir}/../../states.json','r') as ff:
      cfg = json.load(ff)
world_in_glcam = np.array(camera_params['cameraViewTransform']).reshape(4,4).T
cam_in_world = np.linalg.inv(world_in_glcam)@glcam_in_cvcam
world_in_cam = np.linalg.inv(cam_in_world)
objects = cfg['objects']
scale = np.array(objects[ob_name]['scale'])
ob_in_world = np.array(objects[ob_name]['transform_matrix_world']).reshape(4,4).T

def normalizeRotation(pose):
  new_pose = pose.copy()
  scales = np.linalg.norm(pose[:3,:3],axis=0)
  new_pose[:3,:3] /= scales.reshape(1,3)
  return new_pose

ob_in_world = normalizeRotation(ob_in_world)
ob_in_cam = world_in_cam@ob_in_world
```

Here is the code snippet. Hope it helps.

**Comment by W-QY** [comment]
Thanks for the reply! I tried to load the .glb file and the image into blender and reproduce the "ob_in_cam" pose, and here are the results (only R from "ob_in_cam" was used):
![image](https://github.com/user-attachments/assets/b104faf5-3d77-4bb1-af4d-6cc2393a5d12)

Then I tried to rotate the Euler angles of the X axis by 90°, and the result was as follows(The "R" looks correct):
![image](https://github.com/user-attachments/assets/6dd574d4-00ab-4bef-9304-ce4cff60b833)

Here are the camera parameters I set:
![image](https://github.com/user-attachments/assets/f24a0c0e-744e-4fc2-adf2-eb7c5fba03c9)

So the rotation matrix seems to be obtained through conversion, but I can't get the correct translation vector. Do I need to scale the .glb file? Or adjust the camera parameter settings?

**Comment by W-QY** [comment]
Hi, I still can't render the correct image using the translation vector and the .glb mesh file from the objaverse dataset. For example, the "z" in the translation vector of "obj_in_cam" in the above picture is about 1.4, but in blender it needs to be about 5.8m to match the image. 

What should I do with the translation vectors or .glb mesh files?

**Comment by W-QY** [comment]
I did some further experimenting, maybe the .glb file needs similar processing to [MagePose-GSO](https://github.com/thodan/bop_toolkit/issues/98#issuecomment-1718257952)?

**Comment by hiyyg** [comment]
![img_v3_02f3_43787a4d-6081-4a92-987f-af657531628g](https://github.com/user-attachments/assets/1953e631-3984-42da-b674-ba52b90cbe20)
![img_v3_02f3_13377d6a-5304-4a7d-9564-f8961488cd2g](https://github.com/user-attachments/assets/b6d7543a-d4e5-407f-a48e-194773174162)
![img_v3_02f3_eae72c2e-0ef1-4b0e-8620-61203ce8bc3g](https://github.com/user-attachments/assets/88cda018-6aad-47dd-a335-b962bb00afd8)




> I did some further experimenting, maybe the .glb file needs similar processing to [MagePose-GSO](https://github.com/thodan/bop_toolkit/issues/98#issuecomment-1718257952).

Hi, how did you resolve the issue? I did some rendering on the gso data. But many rendered images could not match the provided one.

**Comment by hiyyg** [comment]
> MagePose-GSO

May I ask what specific code is done for processing the objaverse .glb meshes? I could not get the correct scale for rendering.

**Comment by tan-tao11** [comment]
Hi, I meet the same problem in the gso dataset. Could you please tell me more details about processing the mesh model to match the ‘ob_in_cam’?

**Comment by Goddard-Wen** [comment]
I am trying to solve the same problem. Could you tell me more details on how you handled it? It would be very helpful to me if you could share your script. Thank you. @W-QY

**Comment by Exinwww** [comment]
I encountered the same problem, has anyone solved it?
