### ISSUE TITLE
Can the model-free few-shot version work with only RGB and depth image sequences, without target object reference images?

### ISSUE THREAD

**Issue by Sininliny** [NVlabs/FoundationPose#219]
Hello,

I have a question regarding the usage of the model-free few-shot version. Typically, few-shot learning requires reference images of the target object. However, in my use case, it might not be possible to provide reference images of the target object. Therefore, I would like to confirm the following:

Input Data: A sequence of RGB and depth images containing the target object and surrounding scene, but no reference images of the target object. 

Question: In the absence of target object reference images, is it possible to use the model-free few-shot version for processing? 

I would greatly appreciate any insights you can provide.

**Comment by wenbowen123** [comment]
you can check [bundlesdf](https://github.com/NVlabs/BundleSDF)
It does similarly to what you are thinking.
