### ISSUE TITLE
ValueError: string is not a file: /home/zisongxu/FoundationPose/demo_data/mustard0/mesh/textured_simple.obj

### ISSUE THREAD

**Issue by ZisongXu** [NVlabs/FoundationPose#22]
Hi Dear Bowen:

Thanks for the brilliant project. I would like ask a question.

When I run `python run_demo.py` it gives me this error: `ValueError: string is not a file: /home/zisongxu/FoundationPose/demo_data/mustard0/mesh/textured_simple.obj`. I did not see any `demo_data` files under `FoundationPose` folder. Do I need to download something?

Best Regards
Zisong Xu

**Comment by abhishekmonogram** [comment]
Yes you need to download these files 

https://drive.google.com/drive/folders/1pRyFmxYXmAnpku7nGRioZaKrVJtIsroP

**Comment by ZisongXu** [comment]
Thanks a lot!
