### ISSUE TITLE
What filtering method is the best to smooth Angle fluctuations

### ISSUE THREAD

**Issue by ZijianWu1121** [NVlabs/FoundationPose#221]
I placed the object stationary and entered the RGBD in real time with a 30HZ D435i camera. Over time, the pose and angle statistics obtained by FoundationPose are shown in the figure.

What filtering method should I use to remove fluctuating reading stability while reducing the impact on dynamic real-time performance

![1](https://github.com/user-attachments/assets/23f76e2e-b993-48d6-a8fa-f79ca8f2e11f)

**Comment by wenbowen123** [comment]
Hi, is 1deg fluctuation not enough for your application? How does the tracking video look like?
