### ISSUE TITLE
The register process on the Orin NX platform is taking an excessively long time, consuming up to 41 seconds.

### ISSUE THREAD

**Issue by henry0922** [NVlabs/FoundationPose#226]
I've run this codebase on the Orin NX platform, and the latency has increased significantly. However, the main culprit appears to be just a few matrix multiplication operations that take an excessively long time during their first execution. How can I address this issue?

**Comment by wenbowen123** [comment]
For jetson board, you may want to check https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation
