### ISSUE TITLE
Problem when using run_container.sh

### ISSUE THREAD

**Issue by tungyen** [NVlabs/FoundationPose#231]
![image](https://github.com/user-attachments/assets/be0e7780-58e0-48f1-8f7d-bce53a44ef1f)
When I try to run the docker container, it show me the such message. How can I solve this problem? 

And also I think this part of repo should be modified:
![image](https://github.com/user-attachments/assets/5fb6b257-44f2-4da3-985a-e3a41c66bb13)
After cd into docker folder, running command
`bash docker/run_container.sh` will lead to file not found error since I am already in the docker folder.

**Comment by wenbowen123** [comment]
you can ignore that "not found" error. It was just trying to remove the existing container if any.

**Comment by 4goettma** [comment]
@tungyen The error message “No such container” has already been discussed before. Regarding “unable to open display”: Your environment variable “DISPLAY” is probably not set. I assume you are connecting to the computer via SSH. Make sure X11Forwarding is working or temporarily remove the “xhost + && ” from the third line of FoundationPose/docker/run_container.sh to run the Docker container.
