### ISSUE TITLE
Score value goes up during occlusion

### ISSUE THREAD

**Issue by wetoo-cando** [NVlabs/FoundationPose#233]
This is my setup: one object standing on a table with an RGBD camera looking at it.

The score value output by the score network is stable at around 35 (left part of the plot). 
The peaks on the right side are seen when I occlude the object with my hand. I would expect the score value to go down due to the occlusion ("quality of tracking decreases"), however it is going up. 

What is the explanation for this behavior?

Note: throughout the above experiment, the object continues to be tracked pretty well, at least visually.

![image](https://github.com/user-attachments/assets/8a99ad7b-7204-43f6-9c85-ea55e940149f)

**Comment by wenbowen123** [comment]
The score does not have any meaning in absolute value. It was only used to compare relativeness to other pose hypothesis.
