### ISSUE TITLE
Unknown size carton identification

### ISSUE THREAD

**Issue by ST-Break** [NVlabs/FoundationPose#235]
Thank you for your work. At present, I can use your model to detect custom cartons, but my application scenario is visual unpacking, and the carton size to be identified is unknown, because there may be cartons of various sizes on the pallet, as shown below. 
![Snipaste_2024-09-27_17-13-15](https://github.com/user-attachments/assets/775b7821-045c-472d-bfec-68507bce1198)
So I want to know whether this model supports carton recognition with unknown size.

**Comment by wenbowen123** [comment]
Hi, unknown size is not directly supported. However, you can do brute-force, by sampling different scales to the mesh and run each of them, and select the best pose from it.

**Comment by missTL** [comment]
Hello, have you got the real size of the carton?
