### ISSUE TITLE
Zero-Shot Object Detection for 6D Pose Estimation

### ISSUE THREAD

**Issue by eliastreis** [NVlabs/FoundationPose#237]
**Problem**
We're integrating FoundationPose for 6D object pose estimation, which needs a bounding box for the target object. Since we're working with an open set of objects, we want to avoid model re-training/refinement and are looking for a zero-shot object detection model.
We've tried foundational models like DINO, SAM, and their Grounded versions but are still facing issues with reliability and robustness, requiring manual verification.

**Question**
Do you have experience with this / is there a zero-shot detector or related approach which works for you?

**Comment by abhishekmonogram** [comment]
@eliastreis I have tried CNOS and works decently well with the data I have been using FoundationPose for. Check if that works for you
