### ISSUE TITLE
HW recommendation for Foundationpose

### ISSUE THREAD

**Issue by eliastreis** [NVlabs/FoundationPose#238]
I'm looking for recommendations on which camera hardware to use for running Foundationpose. 

We've tested a few affordable cameras like Intel RealSense D405 and D455 on top of our robot arm. 

Do you think using more advanced 3D cameras could improve the results? 

Can you share your experiences with hardware that has worked well for you?

**Comment by wenbowen123** [comment]
yes, better RGBD camera will help. I've used Kinect Azure, and Realsense, and I found Kinect Azure produces slightly better results. But it's a bit harder to setup also.
