### ISSUE TITLE
not good results with realsense camera

### ISSUE THREAD

**Issue by unnamed333user** [NVlabs/FoundationPose#24]
hi @wenbowen123 
I did try foundation pose with data captured from realsense camera. I was using potted meat can object.
The results are quite bad. 
Maybe because of the differences in depth image (between kinect and realsense). Do you have any ideas ?

**Comment by wenbowen123** [comment]
see https://github.com/NVlabs/FoundationPose/issues/25#issuecomment-2037719050

**Comment by wenbowen123** [comment]
It's most likely the data is saved in the wrong format.
