### ISSUE TITLE
How to build a new obj to test?

### ISSUE THREAD

**Issue by wengdunfang** [NVlabs/FoundationPose#243]
Hello, I have an obj file that I drew using SolidWorks (which is a new bottle). In actual scenarios, I used an RGBD camera to capture its RGB images and Depth. At the same time, I generated obj.mtl and corresponding png images using meshlab software. I used the run_demo. py code, but I found that the 3D box detected in the output is completely incorrect, larger than the entire image. May I ask how to build a new obj file? Does this process require fine-tuning of the model?

**Comment by savidini** [comment]
@wengdunfang make sure that your 3D model is scaled in meters. It is probably scaled in millimeters, resulting in the very large detected box. See https://github.com/NVlabs/FoundationPose/issues/44#issuecomment-2048141043 for examples and other possible errors and https://github.com/NVlabs/FoundationPose/issues/44#issuecomment-2049337921 for scaling.
