### ISSUE TITLE
compute_add_err_to_gt_pose

### ISSUE THREAD

**Issue by nishadgothoskar** [NVlabs/FoundationPose#250]
Hi,

We are trying to reproduce the ADD and ADD-S results from the paper, but getting some different numbers for ADD on the symmetric objects.

We found that implementation of `compute_add_err_to_gt_pose` is a placeholder. Can you share more details of how ADD was computed for the paper results?

```
  def compute_add_err_to_gt_pose(self, poses):
    '''
    @poses: wrt. the centered mesh
    '''
    return -torch.ones(len(poses), device='cuda', dtype=torch.float)
```

**Comment by wenbowen123** [comment]
check https://github.com/NVlabs/FoundationPose/blob/main/Utils.py#L232
