### ISSUE TITLE
Update "Env setup option 2: conda (experimental)"

### ISSUE THREAD

**Issue by ZhengYuan-Public** [NVlabs/FoundationPose#254]
For those who has problem set up environment with conda, here are some tips:

- My conda path: `/home/johndoe/miniconda3/`
- My conda env name: `6D`

### Install cuda-toolkit 11.8

```bash
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
```

[Reference](https://github.com/bitsandbytes-foundation/bitsandbytes/issues/212)

### Install GCC 11 (to conda env)

```bash
conda install -c conda-forge gcc=11 gxx=11
```

### Example of `/eigen/path/under/conda`

`/home/johndoe/miniconda3/envs/6D/include/eigen3`

### Modify `bundlesdf/mycuda/setup.py` by adding eigen path to `include_dirs`

```python
setup(
    include_dirs=[
        "/usr/local/include/eigen3",
        "/usr/include/eigen3",
        # Added Conda Eigen path
        "/home/johndoe/miniconda3/envs/6D/include/eigen3",
    ],
)
```

---
You might also need to add the following path

```bash
export LD_LIBRARY_PATH=/home/johndoe/miniconda3/envs/6D/lib:$LD_LIBRARY_PATH
```

**Comment by yiqiaoqingyuyu** [comment]
Hello, thank you for the methods you shared. However, I’m still encountering an issue during the final step of running build_all_conda.sh, specifically when running pip install -e .. I’m wondering if it could be related to the GCC version. Could you kindly share the GCC version you’re using for reference?

**Comment by ZhengYuan-Public** [comment]
> Hello, thank you for the methods you shared. However, I’m still encountering an issue during the final step of running build_all_conda.sh, specifically when running pip install -e .. I’m wondering if it could be related to the GCC version. Could you kindly share the GCC version you’re using for reference?

Yes. The GCC version also matters in the installation. You can try to install GCC 11 by

```terminal
conda install -c conda-forge gcc=11 gxx=11
```

**Comment by yiqiaoqingyuyu** [comment]
> > Hello, thank you for the methods you shared. However, I’m still encountering an issue during the final step of running build_all_conda.sh, specifically when running pip install -e .. I’m wondering if it could be related to the GCC version. Could you kindly share the GCC version you’re using for reference?您好，感谢您分享的方法。但是，在运行 build_all_conda.sh 的最后一步中，特别是在运行 pip install -e 时，我仍然遇到问题。我想知道它是否与 GCC 版本有关。您能否分享一下您正在使用的 GCC 版本以供参考？
> 
> Yes. The GCC version also matters in the installation. You can try to install GCC 11 by是的。GCC 版本在安装中也很重要。您可以尝试通过以下方式安装 GCC 11
> 
> ```
> conda install -c conda-forge gcc=11 gxx=11
> ```

Thank you so much! Following your method and commenting out the first two default eigen3 paths in `include_dirs`, I successfully compiled and ran the program. Without commenting out those paths and only adding my conda eigen3 path, it seemed to mistakenly use the Eigen3 in "usr/local." I truly appreciate your solution!
