### ISSUE TITLE
About scaling

### ISSUE THREAD

**Issue by rorrewang** [NVlabs/FoundationPose#255]
Hi, I have recently been trying to use foundation pose to match multiple scenes. But I encountered some problems. For example, the size of the model I provided is inconsistent with the size of the objects in the captured scene, so it cannot be matched correctly. I found that this problem can be solved by dynamically modifying mesh scale through mesh.apply_scale(scale). Is there any good way to optimize or get the correct scale parameter before the track step?

**Comment by rorrewang** [comment]
I have tried to use the rendered depth from the mesh to get the bbox and compute the scaling rate by divide the two bbox areas, and it works.I wonder is there any better ways to solve it.

**Comment by shruthi-autodesk** [comment]
@rorrewang Can you explain how exactly you solved this or share a code snippet? I've been having this issue for a while.

**Comment by 1270645409** [comment]
> [@rorrewang](https://github.com/rorrewang) Can you explain how exactly you solved this or share a code snippet? I've been having this issue for a while.

@shruthi-autodesk Have you solved this problem? Could you please share your solution? Thanks very much

**Comment by shruthi-autodesk** [comment]
@1270645409 I solved the issue. My mistake was the scale of my depth. Make sure that your CAD model and depth are both in **meters** scale. My CAD and depth were both in millimeters and I scale both of them by 0.001 to convert them to meters, then the model works perfectly.
