### ISSUE TITLE
Coordinate system issue in prediction results

### ISSUE THREAD

**Issue by shirokalu** [NVlabs/FoundationPose#258]
Hello, 
your work has been very helpful to me.
However, I have a question now. I am using a model reconstructed with bundlesdf, and I want to use FoundationPose to guide the robotic arm for grasping. However, in the estimated results, the z-axis is always parallel to the table. Could you please explain what might be causing this, and how I can modify it so that the result can successfully guide the robotic arm for grasping (making the z-axis perpendicular to the table)?

**Comment by wenbowen123** [comment]
can you copy here your visualization? And how does the reconstructed mesh look like for its coordinate system?

**Comment by shirokalu** [comment]
Sorry for the delayed response as I’ve been quite busy recently. I managed to resolve the issue by manually adjusting the model's coordinate system. Thank you so much for your clarification!

**Comment by andrewjjeon** [comment]
@shirokalu How did you adjust the models coordinate system? I am having the same issue as you
