### ISSUE TITLE
run_linemod script keeps running indefinitely

### ISSUE THREAD

**Issue by themozel** [NVlabs/FoundationPose#263]
I have set up everything according to the README and when I run the command:
`python run_linemod.py --linemod_dir /home/themozel/uni/DATASETS/linemod --use_reconstructed_mesh 0`
it just keeps running and never stops. I have waited once up to 3 hours.
I am have a system with RTX4070 super and i5 13600.
Am I missing a step here ?
Would appreciate any help.

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/blob/main/run_linemod.py#L59
this should print progress. Are you seeing it running on new scenes?

**Comment by themozel** [comment]
yeah i can see that,
This is part of the log:

`[to_device()] Moving poses to device cuda:0
[to_device()] Moving scores to device cuda:0
[to_device()] Moving vertex_color to device cuda:0
[to_device()] Moving pos to device cuda:0
[to_device()] Moving faces to device cuda:0
[to_device()] Moving vnormals to device cuda:0
[run_pose_estimation_worker()] 0/1, i_frame:9, ob_id:1
[register()] Welcome
[register()] poses:(252, 4, 4)
[register()] after viewpoint, add_errs min:-1.0
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] pose batch data done
[find_best_among_pairs()] pose_data.rgbAs.shape[0]: 252
[predict()] forward done
[register()] final, add_errs min:-1.0
[register()] sort ids:tensor([ 26,  34,  57,  58,  92,  93, 106, 112, 113, 171, 177, 182, 183, 189,
        190, 195,  21, 172,  25, 153,  33, 225, 109,  69,  28, 242, 237, 110,
         20, 243,  32, 184, 236, 108, 176,  27, 235, 238,  11,  99, 100,  68,
        105,  31,  88,  87, 111, 244,  75,  91,  95, 104, 150, 174,  67, 187,
        230, 241,  18,  74,  98, 149, 120, 128, 231,  94, 179,   3,  49, 180,
        232,  72, 175,  47, 114, 156, 181, 188, 200, 131, 151, 165, 216, 249,
         19,  29,  54,  55,  77, 125, 144, 206,  86, 103,  23,  30,  36,  53,
         83, 155, 161, 185, 192, 196,   6,  78, 102, 116, 122, 132, 162, 186,
        210,   2,   8,  22,  24,  38,  48,  81,  82,  84, 146, 170, 228, 248,
         50,  65,  90, 117, 129, 137, 139, 145, 157, 168, 173, 194, 203, 204,
        220, 251,  13,  15,  39,  45,  51,  52,  56,  62,  63, 118, 124, 130,
        135, 141, 142, 143, 147, 166, 178, 193, 197, 207, 213, 215, 218, 245,
          0,   5,  14,  16,  35,  40,  46,  60,  66,  71,  73,  76,  79,  96,
        101, 119, 121, 123, 126, 148, 152, 159, 163, 164, 198, 201, 202, 209,
        211, 212, 214, 219, 221, 222, 227, 233, 234, 240, 246, 250,   4,   7,
          9,  37,  42,  44,  64,  70,  80, 107, 115, 134, 136, 138, 140, 154,
        158, 160, 191, 205, 208, 226,  10,  12,  41,  61, 217, 224, 229,  17,
         43,  59,  85,  89,  97, 127, 133, 167, 239,   1, 199, 223, 247, 169])
[register()] sorted scores:tensor([83.2031, 83.2031, 83.2031, 83.2031, 83.2031, 83.2031, 83.2031, 83.2031,
        83.2031, 83.2031, 83.2031, 83.2031, 83.2031, 83.2031, 83.2031, 83.2031,
        83.1875, 83.1875, 83.1250, 83.0156, 82.9688, 82.5469, 82.5312, 82.5000,
        82.4844, 82.4844, 82.4688, 82.4531, 82.4219, 82.3906, 82.3594, 82.2969,
        82.2969, 82.2500, 82.2500, 82.2344, 82.2344, 82.2344, 82.2031, 82.2031,
        82.2031, 82.1875, 82.1875, 82.1562, 82.1562, 82.1406, 82.1406, 82.1406,
        82.1250, 82.1250, 82.1250, 82.1250, 82.1250, 82.1250, 82.1094, 82.1094,
        82.1094, 82.1094, 82.0938, 82.0938, 82.0938, 82.0938, 82.0781, 82.0781,
        82.0781, 82.0625, 82.0625, 82.0469, 82.0469, 82.0469, 82.0469, 82.0312,
        82.0312, 82.0156, 82.0156, 82.0156, 82.0156, 82.0156, 82.0156, 82.0000,
        82.0000, 82.0000, 82.0000, 82.0000, 81.9844, 81.9844, 81.9844, 81.9844,
        81.9844, 81.9844, 81.9844, 81.9844, 81.9688, 81.9688, 81.9531, 81.9531,
        81.9531, 81.9531, 81.9531, 81.9531, 81.9531, 81.9531, 81.9531, 81.9531,
        81.9375, 81.9375, 81.9375, 81.9375, 81.9375, 81.9375, 81.9375, 81.9375,
        81.9375, 81.9219, 81.9219, 81.9219, 81.9219, 81.9219, 81.9219, 81.9219,
        81.9219, 81.9219, 81.9219, 81.9219, 81.9219, 81.9219, 81.9062, 81.9062,
        81.9062, 81.9062, 81.9062, 81.9062, 81.9062, 81.9062, 81.9062, 81.9062,
        81.9062, 81.9062, 81.9062, 81.9062, 81.9062, 81.9062, 81.8906, 81.8906,
        81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906,
        81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906,
        81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906, 81.8906,
        81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750,
        81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750,
        81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750,
        81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750,
        81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750, 81.8750,
        81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594,
        81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594,
        81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8594, 81.8438, 81.8438,
        81.8438, 81.8438, 81.8438, 81.8438, 81.8438, 81.8281, 81.8281, 81.8281,
        81.8281, 81.8281, 81.8281, 81.8281, 81.8281, 81.8281, 81.8281, 81.8125,
        81.8125, 81.8125, 81.8125, 81.7969])
[run_pose_estimation_worker()] pose:
[[ 0.1459757   0.9887635  -0.03221244 -0.07045846]
 [ 0.7957165  -0.13669795 -0.5900414  -0.03625123]
 [-0.5878148   0.06049971 -0.80673003  1.0202246 ]
 [ 0.          0.          0.          1.        ]]
[to_device()] Moving pts to device cuda:0
[to_device()] Moving normals to device cuda:0
[to_device()] Moving symmetry_tfs to device cuda:0
[to_device()] Moving rot_grid to device cuda:0
[to_device()] Moving pose_last to device cuda:0
[to_device()] Moving best_id to device cuda:0
[to_device()] Moving poses to device cuda:0
[to_device()] Moving scores to device cuda:0
[to_device()] Moving vertex_color to device cuda:0
[to_device()] Moving pos to device cuda:0
[to_device()] Moving faces to device cuda:0
[to_device()] Moving vnormals to device cuda:0
[run_pose_estimation_worker()] 0/1, i_frame:10, ob_id:1
[register()] Welcome
[register()] poses:(252, 4, 4)
[register()] after viewpoint, add_errs min:-1.0
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] pose batch data done
[find_best_among_pairs()] pose_data.rgbAs.shape[0]: 252
[predict()] forward done
[register()] final, add_errs min:-1.0
[register()] sort ids:tensor([ 25,  26,  34,  57,  58,  92,  93, 105, 106, 112, 113, 171, 177, 182,
        183, 184, 189, 190, 195, 172,  21, 108,  28, 242,  69, 243, 237, 109,
        110,  31, 100, 238, 225,  32, 235, 187,  33, 188, 236,  99, 111, 244,
         88, 239,  24, 107, 151, 104,  29,  87, 241,   8,  27,  72,  86,  98,
        210,  35,  30,  42,  67,  74, 120,  60, 134, 180, 131, 216,  36,  49,
         68,  75, 221,   2,  40,  45,  82, 114, 135, 136, 143, 148, 166, 220,
          5,  18,  22,  39,  47,  52, 118, 124, 141, 156, 174, 219,   3,  10,
         16,  46,  63, 117, 123, 129, 130, 138, 150, 206, 214, 215, 248, 249,
          7,  38, 154, 159, 165, 201, 208, 218,   6,  55,  80,  91,  94, 132,
        137, 144, 168, 191, 193, 204, 207, 213, 226, 245,  14,  48,  51,  56,
         77,  95,  96, 101, 139, 142, 146, 160, 161, 162, 169, 170, 192, 200,
        212, 228, 231, 232, 234, 240, 246,  15,  20,  23,  41,  50,  54,  64,
         76,  81,  85,  90, 119, 122, 125, 140, 147, 152, 155, 175, 178, 186,
        194, 202, 224, 230,   0,  12,  65,  66,  70,  79,  83, 103, 116, 126,
        145, 153, 157, 158, 176, 181, 185, 198, 222,   4,   9,  13,  19,  78,
         84, 133, 163, 179, 209,  44, 102, 121, 173, 196, 197, 205, 211,  11,
         17,  37,  43,  61,  62,  97, 115, 149, 164, 167, 203, 217, 251,  53,
         89, 127, 128, 227, 233,  59,  71, 223, 247, 250, 199, 229,   1,  73])
[register()] sorted scores:tensor([80.3281, 80.3281, 80.3281, 80.3281, 80.3281, 80.3281, 80.3281, 80.3281,
        80.3281, 80.3281, 80.3281, 80.3281, 80.3281, 80.3281, 80.3281, 80.3281,
        80.3281, 80.3281, 80.3281, 80.2188, 80.1719, 79.7031, 79.6719, 79.6406,
        79.6250, 79.6250, 79.6094, 79.5781, 79.5781, 79.5625, 79.5469, 79.5469,
        79.5312, 79.5156, 79.5156, 79.5000, 79.4062, 79.4062, 79.3750, 79.3281,
        79.3125, 79.3125, 79.2969, 79.2969, 79.2656, 79.2656, 79.2344, 79.2031,
        79.1875, 79.1875, 79.1875, 79.1562, 79.1562, 79.1406, 79.1406, 79.1406,
        79.1250, 79.1094, 79.0938, 79.0938, 79.0938, 79.0938, 79.0938, 79.0781,
        79.0781, 79.0781, 79.0625, 79.0625, 79.0469, 79.0469, 79.0469, 79.0469,
        79.0469, 79.0312, 79.0312, 79.0312, 79.0312, 79.0312, 79.0312, 79.0312,
        79.0312, 79.0312, 79.0312, 79.0312, 79.0156, 79.0156, 79.0156, 79.0156,
        79.0156, 79.0156, 79.0156, 79.0156, 79.0156, 79.0156, 79.0156, 79.0156,
        79.0000, 79.0000, 79.0000, 79.0000, 79.0000, 79.0000, 79.0000, 79.0000,
        79.0000, 79.0000, 79.0000, 79.0000, 79.0000, 79.0000, 79.0000, 79.0000,
        78.9844, 78.9844, 78.9844, 78.9844, 78.9844, 78.9844, 78.9844, 78.9844,
        78.9688, 78.9688, 78.9688, 78.9688, 78.9688, 78.9688, 78.9688, 78.9688,
        78.9688, 78.9688, 78.9688, 78.9688, 78.9688, 78.9688, 78.9688, 78.9688,
        78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531,
        78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531,
        78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531, 78.9531,
        78.9531, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375,
        78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375,
        78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375, 78.9375,
        78.9375, 78.9375, 78.9219, 78.9219, 78.9219, 78.9219, 78.9219, 78.9219,
        78.9219, 78.9219, 78.9219, 78.9219, 78.9219, 78.9219, 78.9219, 78.9219,
        78.9219, 78.9219, 78.9219, 78.9219, 78.9219, 78.9062, 78.9062, 78.9062,
        78.9062, 78.9062, 78.9062, 78.9062, 78.9062, 78.9062, 78.9062, 78.8906,
        78.8906, 78.8906, 78.8906, 78.8906, 78.8906, 78.8906, 78.8906, 78.8750,
        78.8750, 78.8750, 78.8750, 78.8750, 78.8750, 78.8750, 78.8750, 78.8750,
        78.8750, 78.8750, 78.8750, 78.8750, 78.8750, 78.8594, 78.8594, 78.8594,
        78.8594, 78.8594, 78.8594, 78.8438, 78.8438, 78.8438, 78.8438, 78.8438,
        78.8281, 78.8281, 78.8125, 78.8125])
[run_pose_estimation_worker()] pose:
[[ 0.17516989  0.9842812  -0.02250071 -0.08008738]
 [ 0.86684453 -0.16502519 -0.4704756  -0.01448906]
 [-0.46679336  0.06290849 -0.8821261   0.9755064 ]
 [ 0.          0.          0.          1.        ]]
[to_device()] Moving pts to device cuda:0
[to_device()] Moving normals to device cuda:0
[to_device()] Moving symmetry_tfs to device cuda:0
[to_device()] Moving rot_grid to device cuda:0
[to_device()] Moving pose_last to device cuda:0
[to_device()] Moving best_id to device cuda:0
[to_device()] Moving poses to device cuda:0
[to_device()] Moving scores to device cuda:0
[to_device()] Moving vertex_color to device cuda:0
[to_device()] Moving pos to device cuda:0
[to_device()] Moving faces to device cuda:0
[to_device()] Moving vnormals to device cuda:0
`

**Comment by wenbowen123** [comment]
`[run_pose_estimation_worker()] 0/1, i_frame:9, ob_id:1 `
this shows the progress. It hasn't finished.

**Comment by themozel** [comment]
As I mentioned this is just part of the log. I ran it again to make sure the print command you mentioned is there. It keeps running indefinitely and never stops that is the issue I am facing. Has this behavior been noticed before ? I can not pinpoint where my issue is

**Comment by ChenC-C** [comment]
Hello, I'm also having this problem. May I ask if you've resolved it?

**Comment by themozel** [comment]
> Hello, I'm also having this problem. May I ask if you've resolved it?

Unfortunately I could not find a solution and authors did not seem to care so I changed my approach and tried other methods.

**Comment by mariapatni** [comment]
I am also having this issue. What other approach did you use?
