### ISSUE TITLE
Question regarding noise distribution for refinement network

### ISSUE THREAD

**Issue by lhy0807** [NVlabs/FoundationPose#271]
Hi Bowen,  could you share a bit more details regarding how you implemented the perturbation noise used to train the refinement network? Specifically, this sentence

> To train the refinement network, the pose is randomly perturbed by adding translation noise under the magnitude of 0.02m, 0.02m, 0.05m for XYZ axis respectively and rotation under the magnitude of 20◦, where the direction is randomized.

Is it the uniform distribution or clipping on a normal distribution?

**Comment by wenbowen123** [comment]
we used uniform. I haven't tried Gaussian but I dont think it will make too big difference.

**Comment by lhy0807** [comment]
Thanks for your response!

**Comment by LoveJu1y** [comment]
@wenbowen123 Hi ,Bowen , in the released refine-net config(2023-10-28-18-33-37), I noticed the model did not use trans_normalizer ,does this mean in the training process , the random noise is not in the uniform distribution of (0.02,0.02,0.05),instead ,the refine process uses mesh_diameter ,so during the training of this weight(2023-10-28-18-33-37) the noise is in the uniform distribution of (-mesh_diameter/2,mesh_diameter/2)?

**Comment by LoveJu1y** [comment]
@wenbowen123 and ，I noticed the diameter always close to 0.2 (because the cad model is normalized) ,so could i just regard the trans_normalizer is(0.1,0.1,0.1)? and the output is not constraineed by tanh
