### ISSUE TITLE
I'm having some problems using my own obj file for testing!

### ISSUE THREAD

**Issue by liiijee-163** [NVlabs/FoundationPose#277]
Here's a video of my attempt, I don't know why it doesn't bbox properly, I'm guessing it's because the input obj file is too large, because I'm using other smaller obj files to try it and it bboxes properly, and the obj file in the case of the problem is around 200k in size.

https://github.com/user-attachments/assets/d8ccff70-ed3e-4670-9cf1-9d1050b8bcce

![微信图片_20241217113610](https://github.com/user-attachments/assets/2d2758e8-e4c6-4aed-a45e-5d28fe62c3c7)

**Comment by Rapxuan** [comment]
你为美年达做了一个mask吗?然后想用来实时检测瓶子类吗

**Comment by liiijee-163** [comment]
> 你为美年达做了一个mask吗?然后想用来实时检测瓶子类吗

Not really, my Minolta is used to test if my camera is valid, the obj model I use corresponds to the object I'm testing, I already know what the problem is, it's because of the size of the obj file, my units are mm

**Comment by Manu752** [comment]
Curious how did you fix this ?
