### ISSUE TITLE
How to run a custom CAD model

### ISSUE THREAD

**Issue by maisalkhatib** [NVlabs/FoundationPose#285]
Hello, thanks for this great work! I want to use this model in any object, I installed a CAD model for a mouse, it has mtl and obj file, and I have this code which works for the mustard and the driller, but doesn't work for my mouse model, I uploaded my code, and the mouse files in this drive: https://drive.google.com/drive/folders/1Z2Inj-vQpHjvm1jq8exLN6qPqYBlGc82?usp=sharing

**Comment by maisalkhatib** [comment]
Hi! I managed to solve the issue. The problem was that I needed to include three files for the model to work correctly: the .obj, the .mtl, and a .png image file. I used Blender to generate these files for my mouse model. Once all three files were included, the model worked perfectly. Thanks again for this great project!

**Comment by ron007d** [comment]
did you created the mask needed for the initialization ?

**Comment by jwd-sbb** [comment]
Which component is using these other two files (.mtl and .png)?
