### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by wetoo-cando** [NVlabs/FoundationPose#29]
@wenbowen123 thanks for the nice work!

From your FoundationPose paper:
"Intel i9-10980XE CPU and NVIDIA RTX 3090 GPU ... pose estimation takes about 1.3 s for one object, where pose initialization takes 4 ms, **refinement takes 0.88 s**, pose selection takes 0.42 s. Tracking runs much faster at ∼32 Hz, since only pose refinement is needed and there are not multiple pose hypotheses. In practice, we can run pose estimation once for initialization and switch to tracking mode for real-time performance."

This part: "Tracking runs much faster at ∼32 Hz, since only pose refinement is needed" seems inconsistent with this: "refinement takes 0.88 s". 

Can you please clarify?

**Comment by unnamed333user** [comment]
@wetoo-cando in tracking mode, there is only the previous pose for refine. But for the first time running, there are so many hypothesis poses for refine (252 poses) so that's why the author said 0.88s for refinement.

**Comment by wenbowen123** [comment]
"since only pose refinement is needed and there are not multiple pose hypotheses"
