### ISSUE TITLE
An error was reported after the docker container was restarted

### ISSUE THREAD

**Issue by wsq1010** [NVlabs/FoundationPose#31]
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

**Comment by wenbowen123** [comment]
did you already solve the problem?

**Comment by wsq1010** [comment]
Hello, I did not solve this problem

**Comment by wsq1010** [comment]
I have another question to ask, what is the data in run_demo saved in ob_in_cam txt file

**Comment by wenbowen123** [comment]
did you restart the container with run_container.sh?

**Comment by wenbowen123** [comment]
the saved data is the pose of the your object model in camera's coordinate frame.

**Comment by tsrobcvai** [comment]
Restarting the container and run "bash build_all.sh" can solve this problem
