### ISSUE TITLE
"CUDA out of memory " in run_demo about kinect_driller_seq 

### ISSUE THREAD

**Issue by cypacjy** [NVlabs/FoundationPose#34]
when i replace the mustard0 with kinect_driller_seq ,it just cant work,and it shows :
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.60 GiB (GPU 0; 7.79 GiB total capacity; 2.63 GiB already allocated; 2.19 GiB free; 2.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
do someone know where to change to fix this problem

**Comment by cypacjy** [comment]
after changing shorter_side to 400 ,i have solve my problem

**Comment by Sgt-Hashtag** [comment]
> after changing shorter_side to 400 ,i have solve my problem

Hey I am getting this problem on mustard0 itself... i mean my memory is less but what do you mean by changing shorter side to 400?

**Comment by abhishekmonogram** [comment]
In run_demo.py, there is a reader object which takes shorter_side argument.
It’s set to None. Change it to a smaller size until you don’t run out of
memory
