### ISSUE TITLE
Only pose estimation No tracking

### ISSUE THREAD

**Issue by abhishekmonogram** [NVlabs/FoundationPose#37]
Hi @wenbowen123 , I have a couple of questions. 
1. I wanted to check if I can do only pose estimation in individual rgbd frames or a sequence of discrete rgbd frames without tracking? If so then could you tell me how to go about it? 

2. I have seen that sometimes tracking fails in one frame and then its very hard to recover the pose from that point on. Is it possible to have a loop where the pose estimation is run every few frames to ensure the tracker and pose estimation are outputting close values, if not then reset the pose to the pose estimation and then continue tracking from that new initialization.

**Comment by wenbowen123** [comment]
1. https://github.com/NVlabs/FoundationPose/blob/97095afa5f92be7cbe584fe3254d682943173947/run_demo.py#L52 this line runs the pose estimation. In run_demo.py we only did this for the first frame, but you can do this for every frame in order to always run estimation no tracking.
2. Do you have the sample data? Curious about what makes it failed. But what you mentioned is feasible.

**Comment by dhanushTDS** [comment]
When doing pose estimation only and no tracking, what is the suggested format for RGB, Depth and the Mask Images. Currently, I have scraped some of your code together like this, but I am getting poor results. 


```
def get_color(image_input):
    color = imageio.imread(image_input)[...,:3]
    color = cv2.resize(color, (480, 640), interpolation=cv2.INTER_NEAREST)
    return color

def get_depth(depth_input):
    depth = cv2.imread(depth_input,-1)/1e3
    depth = cv2.resize(depth, (480, 640), interpolation=cv2.INTER_NEAREST)
    depth[(depth<0.1) | (depth>=np.inf)] = 0
    return depth

def get_mask(mask_input):
    mask = cv2.imread(mask_input,-1)
    if len(mask.shape)==3:
      for c in range(3):
        if mask[...,c].sum()>0:
          mask = mask[...,c]
          break
    mask = cv2.resize(mask, (480, 640), interpolation=cv2.INTER_NEAREST).astype(bool).astype(np.uint8)
    return mask


peg_rgb_image = get_color(rgb_image_path)
depth_image = get_depth(depth_image_path)
mask_image = get_mask(mask_image_path).astype(bool)

cv2.imshow('1', peg_rgb_image)
cv2.waitKey(0)  # Wait indefinitely until a key is pressed
cv2.destroyAllWindows()

pose = est.register(K=rros_camera_I_matrix, rgb=peg_rgb_image, depth=depth_image, ob_mask=mask_image, iteration=est_refine_iter)

center_pose = pose @ np.linalg.inv(to_origin)
vis = draw_posed_3d_box(rros_camera_I_matrix, img=peg_rgb_image, ob_in_cam=center_pose, bbox=bbox)
vis = draw_xyz_axis(peg_rgb_image, ob_in_cam=center_pose, scale=0.1, K=rros_camera_I_matrix, thickness=3, transparency=0, is_input_rgb=True)
# cv2.imshow('1', vis[...,::-1])
cv2.imshow('1', vis)
cv2.waitKey(0)  # Wait indefinitely until a key is pressed
cv2.destroyAllWindows()
```
