### ISSUE TITLE
Questions about dataset and training

### ISSUE THREAD

**Issue by sp9103** [NVlabs/FoundationPose#4]
Thank you for sharing your amazing research! Do you have any plans to share the code for training your model?

Also, could you please explain the format of the dataset you shared? Does it include meshes? I found scene.usd is included, but I'm not sure about object meshes.

**Comment by wenbowen123** [comment]
we do not get permission to release the training part as for now. Will notify if we change the plan.

The mesh names are consistent with the Objaverse (UID) and GSO assets. You need to download those meshes separately though.
