### ISSUE TITLE
Bad performance on streaming video

### ISSUE THREAD

**Issue by JRvilanova** [NVlabs/FoundationPose#40]
Hi all, I am trying to track a custom object, which I added our own .obj model, I am using the following mask (first picture, **click to watch it correctly**). 

When it comes to specific conditions with the same mask and same environment, the performance is nice (have a look at first gif).

However, when the object is missing at the start or dissapears while the tracking is performing, the pose starts to work poorly (take a look at second and third gif).

Thanks in advance! (All gifs are accelerated and second and third are trimmed to meet the 10 mb size).

![0 (1) (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/251c63dd-5802-4d8d-8f7d-fa8ccb40ecaf)

![test_piece_1](https://github.com/NVlabs/FoundationPose/assets/150953922/7b7c4139-3833-48f4-85bb-edd166d2dc88)

![test_piece_3 (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/e7734de5-0b83-44dc-979c-94590114752c)

![test_piece_4 (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/e9ac4328-312e-40e5-bcfd-e330d6863864)

**Comment by wenbowen123** [comment]
What @savidini is right. 

If the object does not appear initially, it does not make sense to do pose estimation. You should first get some 2D detection/segmentation to first check if the object is there. For disappearing in the middle, if it dis-appears for too long, you'd need to rerun pose estimation. If it's short, it may just track fine.

Also, not sure if the speed in the GIF is accelerated. The motion seems pretty big. You can increase the iter number and try again: https://github.com/NVlabs/FoundationPose/blob/97095afa5f92be7cbe584fe3254d682943173947/run_demo.py#L21

**Comment by BXZZcj** [comment]
> Hi all, I am trying to track a custom object, which I added our own .obj model, I am using the following mask (first picture, **click to watch it correctly**).
> 
> When it comes to specific conditions with the same mask and same environment, the performance is nice (have a look at first gif).
> 
> However, when the object is missing at the start or dissapears while the tracking is performing, the pose starts to work poorly (take a look at second and third gif).
> 
> Thanks in advance! (All gifs are accelerated and second and third are trimmed to meet the 10 mb size).
> 
> ![0 (1) (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/251c63dd-5802-4d8d-8f7d-fa8ccb40ecaf)
> 
> ![test_piece_1](https://github.com/NVlabs/FoundationPose/assets/150953922/7b7c4139-3833-48f4-85bb-edd166d2dc88) [ ![test_piece_1](https://github.com/NVlabs/FoundationPose/assets/150953922/7b7c4139-3833-48f4-85bb-edd166d2dc88) ](https://private-user-images.githubusercontent.com/150953922/320821704-7b7c4139-3833-48f4-85bb-edd166d2dc88.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjIwODksIm5iZiI6MTc0MjkyMTc4OSwicGF0aCI6Ii8xNTA5NTM5MjIvMzIwODIxNzA0LTdiN2M0MTM5LTM4MzMtNDhmNC04NWJiLWVkZDE2NmQyZGM4OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNVQxNjU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzMzODY3NzcwOTJjMjVkNjRjNWI4MmQ1ZjMyZWJhNDlhYTlkNDRhNjdiMDU2NjMzMjBiNTQ2NDQ3OGI4NzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fv1a0QHAsWGQ7f3r96J27lcIGmZhYTSLGiCEN3AZjsc) [ ](https://private-user-images.githubusercontent.com/150953922/320821704-7b7c4139-3833-48f4-85bb-edd166d2dc88.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjIwODksIm5iZiI6MTc0MjkyMTc4OSwicGF0aCI6Ii8xNTA5NTM5MjIvMzIwODIxNzA0LTdiN2M0MTM5LTM4MzMtNDhmNC04NWJiLWVkZDE2NmQyZGM4OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNVQxNjU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzMzODY3NzcwOTJjMjVkNjRjNWI4MmQ1ZjMyZWJhNDlhYTlkNDRhNjdiMDU2NjMzMjBiNTQ2NDQ3OGI4NzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fv1a0QHAsWGQ7f3r96J27lcIGmZhYTSLGiCEN3AZjsc)
> 
> ![test_piece_3 (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/e7734de5-0b83-44dc-979c-94590114752c) [ ![test_piece_3 (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/e7734de5-0b83-44dc-979c-94590114752c) ](https://private-user-images.githubusercontent.com/150953922/320825702-e7734de5-0b83-44dc-979c-94590114752c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjIwODksIm5iZiI6MTc0MjkyMTc4OSwicGF0aCI6Ii8xNTA5NTM5MjIvMzIwODI1NzAyLWU3NzM0ZGU1LTBiODMtNDRkYy05NzljLTk0NTkwMTE0NzUyYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNVQxNjU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDU2OTBmY2M4NmJmYjBkOTBjZDg0MWY4MDdhYjBiNjgxMTFjMWFjZjU5NWYzYzc2Yzk3MWE3ZjcwY2E5Yjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sGOpr0K4-CTicqUxeLBg4oqYWMtWKDnjpMtQBJs1Zjc) [ ](https://private-user-images.githubusercontent.com/150953922/320825702-e7734de5-0b83-44dc-979c-94590114752c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjIwODksIm5iZiI6MTc0MjkyMTc4OSwicGF0aCI6Ii8xNTA5NTM5MjIvMzIwODI1NzAyLWU3NzM0ZGU1LTBiODMtNDRkYy05NzljLTk0NTkwMTE0NzUyYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNVQxNjU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDU2OTBmY2M4NmJmYjBkOTBjZDg0MWY4MDdhYjBiNjgxMTFjMWFjZjU5NWYzYzc2Yzk3MWE3ZjcwY2E5Yjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sGOpr0K4-CTicqUxeLBg4oqYWMtWKDnjpMtQBJs1Zjc)
> 
> ![test_piece_4 (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/e9ac4328-312e-40e5-bcfd-e330d6863864) [ ![test_piece_4 (1)](https://github.com/NVlabs/FoundationPose/assets/150953922/e9ac4328-312e-40e5-bcfd-e330d6863864) ](https://private-user-images.githubusercontent.com/150953922/320826140-e9ac4328-312e-40e5-bcfd-e330d6863864.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjIwODksIm5iZiI6MTc0MjkyMTc4OSwicGF0aCI6Ii8xNTA5NTM5MjIvMzIwODI2MTQwLWU5YWM0MzI4LTMxMmUtNDBlNS1iY2ZkLWUzMzBkNjg2Mzg2NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNVQxNjU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjU2MDA0ZjYwZTQ0NDJiOTI3ZmM1N2U0Yzk5ODRjN2U1ZDQ1ZDllYTFlMThhMDM4ZmJkMTE2MDNhOTc2MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZBr7qXg_5EHCl1cUcRTs46zrPtTgYeL6HjprEGZT2mY) [ ](https://private-user-images.githubusercontent.com/150953922/320826140-e9ac4328-312e-40e5-bcfd-e330d6863864.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjIwODksIm5iZiI6MTc0MjkyMTc4OSwicGF0aCI6Ii8xNTA5NTM5MjIvMzIwODI2MTQwLWU5YWM0MzI4LTMxMmUtNDBlNS1iY2ZkLWUzMzBkNjg2Mzg2NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNVQxNjU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjU2MDA0ZjYwZTQ0NDJiOTI3ZmM1N2U0Yzk5ODRjN2U1ZDQ1ZDllYTFlMThhMDM4ZmJkMTE2MDNhOTc2MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZBr7qXg_5EHCl1cUcRTs46zrPtTgYeL6HjprEGZT2mY)

You may try this improved version of FoundationPose to see if it resolves your issue:
[FoundationPose++: Very Simple Tricks Boost FoundationPose Performance in High-Dynamic Scenes](https://github.com/teal024/FoundationPose-plus-plus)
