### ISSUE TITLE
Reason your own model data

### ISSUE THREAD

**Issue by wsq1010** [NVlabs/FoundationPose#42]
Hello I have a question to ask, in addition to the model file and camera calibration parameters and rgb images are also necessary in the reasoning

**Comment by wsq1010** [comment]
Deduce which files are needed in FoundationPose

**Comment by wsq1010** [comment]
Can you tell me how to generate the file under the mask_cosypose path，What are the files in the mask_cosypose path.

**Comment by wenbowen123** [comment]
The files you mentioned are all needed. Refer to run_demo.py for what data are used.

**Comment by wsq1010** [comment]
Hi, I found a problem when extrapolating my own data.It seems that only the results of the first frame of data inference are normal.There are some problems in the subsequent inference graph, may I ask why this is the case?
![1](https://github.com/NVlabs/FoundationPose/assets/108775107/789e6fb6-7c99-436e-b55b-f5d26ebe091c)
![2](https://github.com/NVlabs/FoundationPose/assets/108775107/a6c53c58-9ac4-4965-b69b-04d0ddea96e4)
![8](https://github.com/NVlabs/FoundationPose/assets/108775107/dff0e902-5e6a-4cd3-8ff7-12e2fe030249)
![12](https://github.com/NVlabs/FoundationPose/assets/108775107/a7907226-1453-4b99-9814-bb241e250304)

**Comment by wenbowen123** [comment]
Your data is likely not in the right format. Please check https://github.com/NVlabs/FoundationPose/issues/44#issuecomment-2048141043
