### ISSUE TITLE
Bad performance with custom dataset

### ISSUE THREAD

**Issue by eunseon02** [NVlabs/FoundationPose#48]
Hi, I am trying to test with custom data, but I'm getting poor results. Could you please give me some advice? I used the following data.
[https://drive.google.com/file/d/1wC6HYdqIARZGWh15zdHFizEenMu0kwuf/view?usp=drive_link](url)

I am wondering if it's alright to put RGB camera parameters in the cam_K.txt file, given that the calibration results include both RGB and depth camera parameters

**Comment by wenbowen123** [comment]
All failures I've seen so far are due to the improper data formatting. Please check the great discussion in https://github.com/NVlabs/FoundationPose/issues/44#issuecomment-2048141043. Thanks for the input from @savidini !
