### ISSUE TITLE
Multiple Object 6D Pose Estimation

### ISSUE THREAD

**Issue by zhujingsong** [NVlabs/FoundationPose#5]
I see most of the demos are for just one object. What if there are multiple novel objects?

**Comment by wenbowen123** [comment]
For multi-object, you can run sequentially over each object. See examples in YCB-Video section where there are multiple objects in the scene.

**Comment by ZisongXu** [comment]
@wenbowen123 Hi Bowen, can I track multi-objects at the same time? As my understanding you mean, I can only track single object at once time, if I want to track the second object, I need to re-run the algorithm at the beginning and change the object model to what we want to track? Is that right?

**Comment by wenbowen123** [comment]
@ZisongXu yes that's the simplest. If you want to do that at the same time, you can do multi-processing.

**Comment by ZisongXu** [comment]
@wenbowen123  Thanks a lot!

**Comment by ammar-n-abbas** [comment]
We have implemented multi-object tracking here:

https://github.com/ammar-n-abbas/FoundationPoseROS2
