### ISSUE TITLE
CAD model making？

### ISSUE THREAD

**Issue by 1725917163** [NVlabs/FoundationPose#50]
This is a very interesting work, thank you to the author. I have successfully run it on the sample data set, but there are still problems with custom data. When I use [BundleSDF](https://github.com/NVlabs/BundleSDF) to generate a CAD model, I find that the effect is very poor. The depth camera I use is realsense D450. I guess it may be depth data. It's not easy. I would like to ask the author if there are other ways to create CAD models?

**Comment by wenbowen123** [comment]
what does your object look like, do you have a photo? In general, BundleSDF should work well for a wide range of objects.

**Comment by 1725917163** [comment]
> 你的物体是什么样的，有照片吗？一般来说，BundleSDF 应该适用于各种对象。
Hello, my object is a water glass, as follows:
![451_img_](https://github.com/NVlabs/FoundationPose/assets/58597679/60010da0-b82a-445d-a0fa-fa6f9b982592)
This is the result after rebuilding:
![image](https://github.com/NVlabs/FoundationPose/assets/58597679/afb9daf8-ecee-459f-8709-b6b6b6ff112e)

**Comment by 1725917163** [comment]
> what does your object look like, do you have a photo? In general, BundleSDF should work well for a wide range of objects.

My problem is solved, thank you very much for the author's reply.
