### ISSUE TITLE
getting the mask of first frame without using XMem or SAM as a preprocessing

### ISSUE THREAD

**Issue by monajalal** [NVlabs/FoundationPose#51]
This is a followup question.

Is there a way to make FoundationPose work with only the 2D bounding box of he object of interest? 

Has anyone streamlined it so that there was no need for providing the mask of the first frame as a pre-requisite?

![image](https://github.com/NVlabs/FoundationPose/assets/1892917/149765af-2ce2-4400-8d04-357fbc698efe)

Also, I am not sure how I can provide the pre-req by clicking on one single point on the object. Can someone please walk me through?

**Comment by wenbowen123** [comment]
> Is there a way to make FoundationPose work with only the 2D bounding box of he object of interest?

Yes, you can convert the bbox to a segmentation mask and run the same way. It will work fine. To convert, make the pixels inside the box >0 and background==0.

**Comment by monajalal** [comment]
Thanks for your response. Could you please clarify this or please link me to a reference?

**Yes, you can convert the bbox to a segmentation mask and run the same way. It will work fine. To convert, make the pixels inside the box >0 and background==0.**

**Comment by monajalal** [comment]
Do you expect the performance to drop if I use 2D bbox instead of segmentation mask?

**Comment by wenbowen123** [comment]
Suppose your bbox is [umin, vmin, umax, vmax]
```
mask = np.zeros((height, width), dtype=bool)
mask[vmin:vmax, umin:umax] = 1
```

**Comment by wenbowen123** [comment]
no, it should work as good as the segmentation. I've tried this many times.

**Comment by monajalal** [comment]
@wenbowen123 
Thanks a lot for your guidance. I just wanted to confirm I was able to perform FoundationPose with only 2D bbox of first frame in yolox format and converting it to binary mask.

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/blob/8395bd84adb0bfc3209cb9409e475cd1b51fc17b/run_demo.py#L69C7-L69C18
change this line to `center_pose = pose`

**Comment by abhishekmonogram** [comment]
@wenbowen123 In this case, the generated mask will be completely white. Will it still work?

**Comment by wenbowen123** [comment]
> @wenbowen123 In this case, the generated mask will be completely white. Will it still work?

the area inside the 2D box will be all white, yes, this will be fine.
