### ISSUE TITLE
suggestions for enhancement of results?

### ISSUE THREAD

**Issue by monajalal** [NVlabs/FoundationPose#54]
I have an object that I approach to and middle of capture maybe my camera only sees 20% of it (foundationpose still does pose recognition).

When the object goes back to full view (100% visibility), the mesh is not properly overlaid on it.

Is there a way to improve this such as providing the mask/2D bbox for each frame?

Does this happen on your end too?

Same question for but for slightly more challenging scenario when the object momentarily goes out of view of camera fully.

**Comment by abhishekmonogram** [comment]
@monajalal #37 is related to your question. If you read the run_demo.py there is a conditional statement where the pose estimation is being done only for frame 0 and then for all other frame they run tracking. You can alter the code to do pose estimation for every 5 frames or so or write some heuristics to see where the object is.  If you can provide with mask in each frame, then you can use it to get accurate poses. There is a possibility it may still fail, but worth a try.

**Comment by wenbowen123** [comment]
In my own experience, it's quite robust to occlusions (even <20% visible).

When the object momentarily goes out of view of camera fully, if this period is short, it may just find it back fine with tracking. But if it happens long, you need to rerun pose estimation.
