### ISSUE TITLE
regarding orientation and showing the top of object

### ISSUE THREAD

**Issue by monajalal** [NVlabs/FoundationPose#55]
In the following photo, shouldn't the blue line be up to show the top of the object?

![image](https://github.com/NVlabs/FoundationPose/assets/1892917/4d8edfe0-4f17-4f6f-acb5-9832b99abaa7)

I may be wrong but I was under the assumption that blue line should be up no down.

Here is an example that is more intuitive to me

![image](https://github.com/NVlabs/FoundationPose/assets/1892917/1f2d5c42-1927-464f-a783-de7640733da2)

http://jiazewang.com/projects/6DPoseEstimation.html

Also I notice yours in README.md is correct 

![image](https://github.com/NVlabs/FoundationPose/assets/1892917/584549fe-2e94-41c3-a416-660c5b8f8821)

I am trying to understand what may have gone wrong when reproducing the results for Mustard0.

Thanks a lot for any clarification

**Comment by wenbowen123** [comment]
There is no right or wrong here. It all depends on how you define the coordinate system. The key is the estimated output is consistent with your CAD model (import it into NVIDIA Omniverse and check its coordinate), and it's consistent along the frames during tracking. What you mentioned Z axis up is just one common habit.

**Comment by monajalal** [comment]
Bowen,

Thanks for your explanation. I think my confusion comes from the fact that I am using the same exact mustard data but I am getting different visualization results than yours. 

Is there a way that using your data of mustard0 I get the same exact visualization?

I haven't changed anything in your data.

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/blob/8395bd84adb0bfc3209cb9409e475cd1b51fc17b/run_demo.py#L69
change to 
`center_pose = pose`

**Comment by monajalal** [comment]
Your code change makes the orientation correct for the mustard object but when I try it for my own custom object, it moves the bounding box around. I email you a photo of what happened to my object.

![image](https://github.com/NVlabs/FoundationPose/assets/1892917/4eb5f882-1a4c-4b4a-8edd-b46693955921)

**Comment by wenbowen123** [comment]
as discussed in the email, you can modify the mustard 3D model to make the z axis up and axis-aligned. Note that all of this is for viz only, it wont affect the way you use it for tasks such as robot grasping.
