### ISSUE TITLE
How to export to tensorrt

### ISSUE THREAD

**Issue by RainRoboforce** [NVlabs/FoundationPose#56]
Thanks @wenbowen123 for the great work! I have tested it on my scenarios and works fantastic!
Just want to ask if there are any instructions for exporting the model to tensorrt? Or any insights would be helpful!

**Comment by wenbowen123** [comment]
this will soon be released in NVIDIA Isaac SDK https://developer.nvidia.com/isaac/manipulator

**Comment by RainRoboforce** [comment]
Thanks for the reply! I am new to pytorch. A naive question: if I want to test the model in c++ programs. Can I use torchscript to save the weights and load them in c++?

**Comment by monajalal** [comment]
@wenbowen123 I am also interested in learning how to run your model on Jetson. If you may be able to share instructions for running this on Jetson or converting it to trt would be great.

**Comment by wenbowen123** [comment]
Isaac manipulator has released! They provide acceleration including TensorRT

**Comment by zz990099** [comment]
I rewrote a [C++ implementation code](https://github.com/zz990099/foundationpose_cpp) for FoundationPose with TensorRT based on the [issac_pose_estimation](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation) project, removing many complex dependencies to make it easier to use. I'm glad if it helps you!
