### ISSUE TITLE
Not understanding the docker commands (noob)

### ISSUE THREAD

**Issue by jkim447** [NVlabs/FoundationPose#57]
This is my first time using docker and after some research I'm still struggling to make progress here. Some guidance would be useful. 

In your read me you suggested the following:

![Screenshot from 2024-04-13 21-43-12](https://github.com/NVlabs/FoundationPose/assets/16571871/df2c772a-fce8-43d2-852f-fd203a2cb2c1)

But what is confusing here is that after I run the container using the suggested "bash docker/container.sh", the whole git repo is gone in the new terminal and thus I cannot execute the next command "bash build_all.sh". Clearly I must be missing something obvious here. Any suggestions would be helpful.

**Comment by jkim447** [comment]
One way I've gotten around this is by mounting my own local directory by editing the run_container.sh file.

For instance, you can add the line `-v /home/your_home_directory:/home/your_home_directory`, where "your_home_directory" is probably your user name. I wonder if something like this is standard procedure and so it was not mentioned in the readme.

**Comment by wenbowen123** [comment]
yes, this is the right way to do. You can mount your local path to access in docker container. So you can mount the repo's located dir too.
