### ISSUE TITLE
Clear explanation needed of what is possible with this model (given certain inputs)

### ISSUE THREAD

**Issue by jkim447** [NVlabs/FoundationPose#58]
Thank you for the great work. It is not super clear which inputs are absolutely necessary for pose estimation here. If I have RGB (no depth) and a 3D CAD model, can I use your model? Or would I need further input modalities here?

**Comment by abhishekmonogram** [comment]
It is mentioned in the paper that Foundation Pose is rgbd based method and will require a depth map. 

> In this paper we propose a unified framework called FoundationPose that performs both pose estimation and tracking  for novel objects in both the model-based and model-free setups, using RGBD images

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/issues/77
