### ISSUE TITLE
CUDA and pytorch version mismatch

### ISSUE THREAD

**Issue by aThinkingNeal** [NVlabs/FoundationPose#6]
Hi, when I run the codebase I encountered the problem of mismatch version of CUDA and pytorch.

When I check the dockerfile I notice that the cuda version is 11.3 and pytorch is for 11.8, should this be updated?

![image](https://github.com/NVlabs/FoundationPose/assets/31988374/9d049b6e-6ce1-4e6f-8ec1-74a935520fa3)

![image](https://github.com/NVlabs/FoundationPose/assets/31988374/ee1aabd8-d421-4c91-8e0c-ecbcc121ad74)

**Comment by wenbowen123** [comment]
Hi, we did not have any issue when running on 3090, V100, A100 etc. If you bump into errors, you can try to change that.

**Comment by Siddharth-rs** [comment]
@aThinkingNeal how did you solve this issue?

**Comment by aThinkingNeal** [comment]
> @aThinkingNeal how did you solve this issue?

You could check this issue :)

[Issue 27](https://github.com/NVlabs/FoundationPose/issues/27)
