### ISSUE TITLE
Is there a easy way to make a ycb-video format data ?

### ISSUE THREAD

**Issue by 52THANOS** [NVlabs/FoundationPose#60]

**Comment by 52THANOS** [comment]
I only have a rgb camera

**Comment by ysdagar** [comment]
By any chance have you come across this? https://docs.omniverse.nvidia.com/isaacsim/latest/replicator_tutorials/tutorial_replicator_offline_pose_estimation.html

**Comment by 52THANOS** [comment]
> By any chance have you come across this? https://docs.omniverse.nvidia.com/isaacsim/latest/replicator_tutorials/tutorial_replicator_offline_pose_estimation.html

I have tried this method. however it can not generate all Material. Especially i have to use my own object.  FDpose's data_reader has specified the data format.  Or is there something i missed in isaacsim

**Comment by wenbowen123** [comment]
For your own project, I'd recommend to closely follow our provided demo data format. It's simpler and more concise than YCB-Video.

**Comment by ysdagar** [comment]
Thank you @wenbowen123 so much! Is there any automated way to generate the data similar to demo data format from Isaac Sim? something similar to https://docs.omniverse.nvidia.com/isaacsim/latest/replicator_tutorials/tutorial_replicator_offline_pose_estimation.html

**Comment by 52THANOS** [comment]
> For your own project, I'd recommend to closely follow our provided demo data format. It's simpler and more concise than YCB-Video.

how do you make your own data?

**Comment by wenbowen123** [comment]
> Thank you @wenbowen123 so much! Is there any automated way to generate the data similar to demo data format from Isaac Sim? something similar to https://docs.omniverse.nvidia.com/isaacsim/latest/replicator_tutorials/tutorial_replicator_offline_pose_estimation.html

I dont think there is automatic way for now. But you can get all the required data from the simulator and write in the correct format.

**Comment by 52THANOS** [comment]
> > Thank you @wenbowen123 so much! Is there any automated way to generate the data similar to demo data format from Isaac Sim? something similar to https://docs.omniverse.nvidia.com/isaacsim/latest/replicator_tutorials/tutorial_replicator_offline_pose_estimation.html
> 
> I dont think there is automatic way for now. But you can get all the required data from the simulator and write in the correct format

but i dont want to use simulator. how to creat data format using my own object assets? Is there a tool?

**Comment by wenbowen123** [comment]
by simulator I mean Isaac Sim. You can use that to export. It will have everything you need, you just need to reformat a bit to be compatible with FoundationPose.
