### ISSUE TITLE
Error when run run_demo.py? 

### ISSUE THREAD

**Issue by aghaphd** [NVlabs/FoundationPose#61]
Traceback (most recent call last):
  File "/home/ali/FoundationPose/run_demo.py", line 52, in <module>
    pose = est.register(K=reader.K, rgb=color, depth=depth, ob_mask=mask, iteration=args.est_refine_iter)
  File "/home/ali/FoundationPose/estimater.py", line 173, in register
    depth = erode_depth(depth, radius=2, device='cuda')
NameError: name 'erode_depth' is not defined

Thanks.

**Comment by wenbowen123** [comment]
are you running inside a docker? Did you install warp package?

**Comment by aghaphd** [comment]
Thank you for your response, actually not using the docker. I started the implementation from option 2.  Where Warp package mentioned? I mean which step?

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/blob/main/requirements.txt#L79
It's mentioned in option2

**Comment by aghaphd** [comment]
I successfully run it through the Docker.
