### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by LuLuc** [NVlabs/FoundationPose#63]
I follow the installation instructions with anaconda for the model free version.

When I run "python bundlesdf/run_nerf.py --ref_view_dir ../YCB_Video/ref_views_16 --dataset ycbv". The training start and after some time (~20min) it crashes during training with "free(): invalid pointer".

This is the last lines I have in the terminal:

[extract_mesh()] query_pts:torch.Size([54872, 3]), valid:54872
[extract_mesh()] Running Marching Cubes
[extract_mesh()] done V:(4062, 3), F:(8116, 3)
[extract_mesh()] query_pts:torch.Size([54872, 3]), valid:54872
[extract_mesh()] Running Marching Cubes
[extract_mesh()] done V:(4062, 3), F:(8116, 3)
[mesh_texture_from_train_images()] Texture: Texture map computation
project train_images 0/16
project train_images 1/16
project train_images 2/16
project train_images 3/16
project train_images 4/16
project train_images 5/16
project train_images 6/16
project train_images 7/16
project train_images 8/16
project train_images 9/16
project train_images 10/16
project train_images 11/16
project train_images 12/16
project train_images 13/16
project train_images 14/16
project train_images 15/16
/home/luc/FoundationPose/bundlesdf/nerf_runner.py:1227: RuntimeWarning: invalid value encountered in cast
  tex_image = np.clip(tex_image,0,255).astype(np.uint8)
free(): invalid pointer
[1]    21958 IOT instruction  python bundlesdf/run_nerf.py --ref_view_dir  --dataset ycbv

**Comment by wenbowen123** [comment]
you can ignore that msg. As long as you are able to see the results saved, it's fine.
