### ISSUE TITLE
time required for processing the video in different scenarios

### ISSUE THREAD

**Issue by monajalal** [NVlabs/FoundationPose#64]
I would like to know what is the time it takes for you approximately for similar length video and if there is a way to even make it faster?

input: a 2.8 minutes 

took 6.42 minutes if pose estimation only on first frame

took 7.28 minutes if pose estimation only on first frame and setting track_refine_iter to 5

Capture is done with Intel RealSense D435 camera.

**Comment by wenbowen123** [comment]
Did you include the IO time? Did you disable all debug loggings? What's the complexity of your mesh? All these can influence. Also you should consider the NVIDIA SDK which provides much faster running time.

**Comment by monajalal** [comment]
What do you mean by "NVIDIA SDK"? Do you mean https://github.com/NVlabs/FoundationPose/issues/56#issuecomment-2053732961 since it is not yet released.

Thanks for all the pointers. Yes, I should stop the debug times.  I will report back later.

**Comment by monajalal** [comment]
Thanks a lot for your input.

After removing `--debug 3`:

input: a 2.8 minutes

took 2.1 minutes if pose estimation only on first frame

took 3.14 minutes if pose estimation only on first frame and setting track_refine_iter to 5


I took the time when the visualization starts on the screen. I am very happy with processing time. Thanks.
