### ISSUE TITLE
Hi, I want to know what each value of the matrix that returns pose(4*4) represents

### ISSUE THREAD

**Issue by wsq1010** [NVlabs/FoundationPose#67]
pose = est.track_one(rgb=color, depth=depth, K=reader.K, iteration=args.track_refine_iter)
pose = est.register(K=reader.K, rgb=color, depth=depth, ob_mask=mask, iteration=args.est_refine_iter)

**Comment by wenbowen123** [comment]
it's the homogeneous matrix.
