### ISSUE TITLE
My ram is full before I start the container and the Files tag within the Container is continuously refreshing container files.

### ISSUE THREAD

**Issue by Hanning-Liu** [NVlabs/FoundationPose#69]
![image](https://github.com/NVlabs/FoundationPose/assets/42676581/aae1aa75-9424-45d1-a4df-18909ddcc2ea)

**Comment by Hanning-Liu** [comment]
I'm new to docker, hope someone can help me with this!

**Comment by wenbowen123** [comment]
How big is your total RAM?

**Comment by Hanning-Liu** [comment]
> How big is your total RAM?

Hi @wenbowen123. Thank you for your reply.
The screenshot is from my laptop which has a 16gb ram. I also tried on another desktop with 32gb ram, but the situation is the same.

**Comment by wenbowen123** [comment]
does the refreshing affect your usage inside docker?

**Comment by Hanning-Liu** [comment]
Hi @wenbowen123 
It keeps refreshing and never stop🤦‍♂️.
I uploaded a screen recording to YouTube: https://youtu.be/4C1_0QG_XPs.

**Comment by Hanning-Liu** [comment]
![image](https://github.com/NVlabs/FoundationPose/assets/42676581/d532fccf-2250-43a0-8fab-bfeb0812c120)
![image](https://github.com/NVlabs/FoundationPose/assets/42676581/2bb53869-1f05-4993-a6d4-56ccf092503f)

**Comment by wenbowen123** [comment]
this is more like a Windows docker issue. 

This seems related https://github.com/docker/for-win/issues/12266

Also, if you have a Linux machine, using that would be easiest.
