### ISSUE TITLE
kaolin for build -- build_all.sh: line 4: cd: /kaolin: No such file or directory

### ISSUE THREAD

**Issue by monajalal** [NVlabs/FoundationPose#7]
```
(foundationpose) mona@ada:/data/FoundationPose$ bash build_all.sh
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found pybind11: /usr/local/include (found version "2.12.0dev1")
-- Configuring done
-- Generating done
-- Build files have been written to: /data/FoundationPose/mycpp/build
[ 33%] Building CXX object CMakeFiles/mycpp.dir/src/app/pybind_api.cpp.o
[ 66%] Building CXX object CMakeFiles/mycpp.dir/src/Utils.cpp.o
/data/FoundationPose/mycpp/src/app/pybind_api.cpp: In function ‘vectorMatrix4f cluster_poses(float, float, const vectorMatrix4f&, const vectorMatrix4f&)’:
/data/FoundationPose/mycpp/src/app/pybind_api.cpp:26:38: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
   26 |   printf("num original candidates = %d\n",poses_in.size());
      |                                     ~^    ~~~~~~~~~~~~~~~
      |                                      |                 |
      |                                      int               std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type {aka long unsigned int}
      |                                     %ld
/data/FoundationPose/mycpp/src/app/pybind_api.cpp:66:42: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
   66 |   printf("num of pose after clustering: %d\n",poses_out.size());
      |                                         ~^    ~~~~~~~~~~~~~~~~
      |                                          |                  |
      |                                          int                std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type {aka long unsigned int}
      |                                         %ld
[100%] Linking CXX shared module mycpp.cpython-39-x86_64-linux-gnu.so
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
[100%] Built target mycpp
build_all.sh: line 4: cd: /kaolin: No such file or directory
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///data/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  Running setup.py develop for common
Successfully installed common-0.0.0

```

**Comment by wenbowen123** [comment]
if you are not using model-free version, you can comment these line 
```
cd /kaolin && rm -rf build *egg* && pip install -e .
cd $DIR/bundlesdf/mycuda && rm -rf build *egg* && pip install -e .
```
https://github.com/NVlabs/FoundationPose/blob/main/build_all.sh#L4

**Comment by Jingranxia** [comment]
********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************


Hello author, I encountered this issue while compiling the bundlesdf package. How can I solve this problem

**Comment by Jingranxia** [comment]
@wenbowen123

**Comment by Sgt-Hashtag** [comment]
> if you are not using model-free version, you can comment these line
> 
> ```
> cd /kaolin && rm -rf build *egg* && pip install -e .
> cd $DIR/bundlesdf/mycuda && rm -rf build *egg* && pip install -e .
> ```
> 
> https://github.com/NVlabs/FoundationPose/blob/main/build_all.sh#L4

So can we ignore both of these lines ?

Since when I run the last line I get an error since don't have a torch installed in my base env
Obtaining file:///home/adas/Desktop/temp/6DPose/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/adas/Desktop/temp/6DPose/FoundationPose/bundlesdf/mycuda/setup.py", line 12, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
