### ISSUE TITLE
About the coordinate frame of target object

### ISSUE THREAD

**Issue by ZisongXu** [NVlabs/FoundationPose#72]
Hi Dear, I have a question about the coordinate frame of the result of the target object.

This is the model I feed into the FoudationPose system, and we can see the coordinate frame clearly.
![Screenshot from 2024-04-19 15-19-38](https://github.com/NVlabs/FoundationPose/assets/36726128/d4c7f555-dd99-4e6b-9933-1df93a7868f7)

But what I get in the result is:
![Screenshot from 2024-04-14 19-45-54](https://github.com/NVlabs/FoundationPose/assets/36726128/ee6fa8e2-2a35-4432-83bf-546b8d147970)

We can see the difference between the coordinate frame of .obj model file and the coordinate frame of result.

And I also check the example you provided, this is the model:

![Screenshot from 2024-04-19 15-27-28](https://github.com/NVlabs/FoundationPose/assets/36726128/9530cc64-9f89-4493-8929-e3c58fc47c22)

This is the result:

![Screenshot from 2024-04-19 15-26-13](https://github.com/NVlabs/FoundationPose/assets/36726128/ea485e68-e9dc-4dc5-b053-128564c01735)

Also different, is that right or should I set the coordinate frame some where before running FoudationPose system?

Thanks a lot!
Best Regards
Zisong XU

**Comment by ZisongXu** [comment]
By the way, about the results, we can get the object pose in camera. Can you tell me the coordinate frame of the camera. Because I need to convert the object pose in camera to object pose in world frame so I can use this system.

**Comment by wenbowen123** [comment]
You can disable this line https://github.com/NVlabs/FoundationPose/blob/8395bd84adb0bfc3209cb9409e475cd1b51fc17b/run_demo.py#L69 which may change the coordinate.

However, the pose being saved is still correct https://github.com/NVlabs/FoundationPose/blob/8395bd84adb0bfc3209cb9409e475cd1b51fc17b/run_demo.py#L66

**Comment by wenbowen123** [comment]
it's using OpenCV camera coordinate system: https://stackoverflow.com/questions/17987465/how-is-the-camera-coordinate-system-in-opencv-oriented

**Comment by ZisongXu** [comment]
Thanks a lot!

**Comment by shirokalu** [comment]
> Thanks a lot!
Sorry for commenting on a closed issue. I would like to ask if you solved it using the method mentioned above, and did the robotic arm ultimately use the "pose" directly?

**Comment by shirokalu** [comment]
Thank you very much for your response; it was very helpful to me. I successfully resolved the issue!
