### ISSUE TITLE
Issue with Ground Truth Data in YCB Dataset

### ISSUE THREAD

**Issue by Sar-thak-3** [NVlabs/FoundationPose#74]
### Description:

I encountered an issue while attempting to access ground truth data for the YCB dataset when running the `run_ycb_video.py` script. Despite following the provided directory structure and documentation, I couldn't find the necessary ground truth files.
```
- test
  - 000048
    - RGB
    - depth
    - mask
    - screen_gt.json
    - screen_gt_info.json
    - scene_camera.json
  - keyframes.txt
  - validation.txt
- testval.txt
```

The output produced by the model is in the form of a `4x4` array.

I would appreciate guidance on where to find the ground truth file if it is not present in the expected directory.

**Comment by wenbowen123** [comment]
You need to download the dataset separately from https://bop.felk.cvut.cz/datasets/ which includes the GT
