### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by QiHaoYao** [NVlabs/FoundationPose#75]
Hi, when running run_demo.py, I get an error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/robot726/Ginger/FoundationPose/weights/2024-01-11-20-02-45/config.yml'
please tell me where is the "config.yml",thank u

**Comment by tsrobcvai** [comment]
https://drive.google.com/drive/folders/1DFezOAD0oD1BblsXVxqDsl8fj0qzB82i?usp=sharing

**Comment by Bailey-24** [comment]
https://blog.csdn.net/m0_56661101/article/details/137921028
