### ISSUE TITLE
Not working on Jetson having Jetpack 4.6

### ISSUE THREAD

**Issue by gautam1858** [NVlabs/FoundationPose#79]
Hi,

How to run FoundationPose on Jetpack 4.6 having python version 3.6.6 and torch 1.0 ? I cannot upgrade the jetpack 4.6 since it has lot of other dependencies.

-GR

**Comment by wenbowen123** [comment]
Hi, Isaac Manipulator supports Jetpack 6. You may want to check out https://developer.nvidia.com/isaac/manipulator
