### ISSUE TITLE
How to generate material.mtl and material.png files

### ISSUE THREAD

**Issue by Wahaha-code** [NVlabs/FoundationPose#84]
Great work! 
Now, I don't know how to generate material.mtl and material.png files in the mesh folder, I currently have obj files.

**Comment by wenbowen123** [comment]
You can use BundleSDF to build a textured mesh https://github.com/NVlabs/BundleSDF

**Comment by shruthibalaji2307** [comment]
@wenbowen123 I have an existing textured CAD model of an object as an STL file. How do I get the .mtl and .png files for it? BundleSDF is used when we don't have a 3d model for the object right?

**Comment by wenbowen123** [comment]
https://www.reddit.com/r/3Dprinting/comments/d084ob/adding_texture_to_stl_files_need_advice/
there are plenty of ways to do this. You can search more.
