### ISSUE TITLE
How can I obtain an initial mask?

### ISSUE THREAD

**Issue by cfcy-zch** [NVlabs/FoundationPose#88]
I'm a beginner. I have a physical YCB model, and I can obtain depth and RGB data through an RGBD camera. However, I don't know how to obtain the initial mask. Are there any relevant functions in the program that can calculate the initial mask?

**Comment by wenbowen123** [comment]
Hi, you can use SAM/CNOS/Mask-RCNN to get segmentation mask directly. Or you can use a bounding box as mentioned in https://github.com/NVlabs/FoundationPose/issues/51
