### ISSUE TITLE
run_nerf.py error "[WARNING] batch has 0 intersections!!"

### ISSUE THREAD

**Issue by Celinna** [NVlabs/FoundationPose#90]
Hello,

Thank you for the great work. 

I am trying to generate the textured mesh and .obj file of a custom object with 16 reference images. I collected rgb, depth (aligned), segmentation masks, and pose (object wrt. camera) data. I get "[WARNING] batch has 0 intersections!!" when running run_nerf.py on this data.

I suspect the object poses are not in the correct form. Could you clarify how to get the data in the cam_to_ob folder for model-free implementations?

Thanks

**Comment by wenbowen123** [comment]
you may need to get the inverse pose, see https://github.com/NVlabs/FoundationPose/issues/49#issuecomment-2068038921

**Comment by Celinna** [comment]
Hello,

Thank you your suggestion worked!
