### ISSUE TITLE
Some issues with the custom dataset

### ISSUE THREAD

**Issue by tobottyx** [NVlabs/FoundationPose#92]
Thank you for your excellent work.I followed the guidelines from #44 to collect data, but encountered some issues. First, there is a significant discrepancy between the size of the bounding boxes and the actual size of the objects. Secondly, the pose accuracy is not precise, and when I manually adjust the objects, the pose is unstable. I have double-checked all my files, including the format of the depth maps. I used the obj model from ycb-v, and aligned the color and depth images. I would like to thank  the auther and @savidini  for your help.

https://github.com/NVlabs/FoundationPose/assets/150102559/af69df68-45d7-4131-ac5f-ff866ebca240

Here are some of my results. Below are some .ply files from debugging. I hope the author can take a look for me. Thank you very much.
https://drive.google.com/file/d/1cNCCbVohiq45m27u3c_SrCDTo2bU9YC5/view

**Comment by tobottyx** [comment]
![0000000000](https://github.com/NVlabs/FoundationPose/assets/150102559/2eb0751c-5190-415e-9657-e05377d9d4a7)

**Comment by wenbowen123** [comment]
your depth image is wrong. The point cloud is in the wrong scale and skewed.

**Comment by tobottyx** [comment]
Thank you very much for your answer, I will modify and try again
