### ISSUE TITLE
Error while running the run_demo.py file for a novel object (model based) metall-block

### ISSUE THREAD

**Issue by kobold2301** [NVlabs/FoundationPose#93]
Hello and thank you for making this code publicly available.

I encountered issues while trying to reproduce tracking on a custom dataset. The provided examples work perfectly, but I'm facing challenges with my setup. I've already investigated potential issues related to object scaling, depth, and mask data, which are similar to those discussed in other issues.

I've included my Blender project, which features a metal cube with real dimensions of 60x60x70 mm. In Blender, the dimensions are set to 60x60x70 meters, and I've scaled it down using Trimesh in a Jupyter Notebook (code included). All my test data is available in the debug folder, accessible via this Google Drive link[1].

[1] https://drive.google.com/drive/folders/1SgsxgqZBmG1REdSzgLKGF2LUjWEtgDa7?usp=sharing

Here is an image of the tracked object, initially scaled down from 60 meters to 60 mm by a factor of 1000. Since it still appeared somewhat large, I also have a version scaled down by a factor of 10,000.

Scale 10000:
![1_screenshot_26 04 2024](https://github.com/NVlabs/FoundationPose/assets/32896111/99c45d9d-9920-4880-9524-8a11bb43182c)

Scale 1000:
![1_screenshot_28 04 2024](https://github.com/NVlabs/FoundationPose/assets/32896111/2d693c22-4d91-41b5-892c-d5bda3146cba)

![Bildschirmfoto vom 2024-04-28 13-23-07](https://github.com/NVlabs/FoundationPose/assets/32896111/fadb6671-3e9b-46af-9564-41be9f8b099a)

**Comment by wenbowen123** [comment]
your depth is wrong, you can viz the `scene_complete.ply` file in the debug_dir.
