### ISSUE TITLE
bad result with custom data

### ISSUE THREAD

**Issue by eunseon02** [NVlabs/FoundationPose#94]
I am testing with my custom data, but the tracking results are poor, as you can see below. Please take a look at the video after the 10-second mark.

[Screencast from 04-29-2024 01_02_51 AM.webm](https://github.com/NVlabs/FoundationPose/assets/108911413/f42308b8-68e5-49d9-99d3-30fce648d72f)

i attached my dataset folder
https://drive.google.com/file/d/1bCer4uM1yyu9qPbB3Er2UBByZz7rNDs5/view?usp=sharing

I'm using the code from the comment https://github.com/NVlabs/FoundationPose/issues/44#issuecomment-2048141043 to generate data

**Comment by cypacjy** [comment]
me too .when i use the tracking style .the first frames goes well.but when time goes by.the pose goes wrong.
![0](https://github.com/NVlabs/FoundationPose/assets/52927900/377b66c5-97e4-4d6d-b969-034ba7c19b96)
i think it may be caused by the model with little characters .the solution still have not be founded

**Comment by wenbowen123** [comment]
can you send your debug_dir for further check? Similar to https://github.com/NVlabs/FoundationPose/issues/83#issuecomment-2079709973

**Comment by eunseon02** [comment]
this is debugging info 

https://drive.google.com/file/d/1jz_enCMsNgU42cdDStp0uuwUd6ELVoBF/view?usp=drive_link

**Comment by eunseon02** [comment]
this is debugging info

https://drive.google.com/file/d/1jz_enCMsNgU42cdDStp0uuwUd6ELVoBF/view?usp=drive_link

> can you send your debug_dir for further check? Similar to [#83 (comment)](https://github.com/NVlabs/FoundationPose/issues/83#issuecomment-2079709973)

**Comment by eunseon02** [comment]
this is debug folder
https://drive.google.com/file/d/1m3r68X6qD39excPoWWXjeba4Ly07EOGp/view?usp=drive_link

**Comment by wenbowen123** [comment]
you did not allow permission

**Comment by wenbowen123** [comment]
when you run FoundationPose, your model texture is not loaded. See vis_refiner.png

**Comment by eunseon02** [comment]
i retried with another data(masking mesh file by bundlesdf, and using code of #44 )
but not works well. 

https://github.com/NVlabs/FoundationPose/assets/108911413/649b7687-2a50-46c2-8357-91d7f3f9a686


this is debug folder

**Comment by eunseon02** [comment]
> when you run FoundationPose, your model texture is not loaded. See vis_refiner.png

**Comment by liuchangji** [comment]
@eunseon02  Hi, did you solve your tracking problem and if you solved it how you did?
