### ISSUE TITLE
what's the meaning of cam_in_ob

### ISSUE THREAD

**Issue by AndrewSmithWalter** [NVlabs/FoundationPose#96]
/demo_data/ref_views_4/ob_0000001/cam_in_ob
I want to make my own dataset, but I don't know what the cam_in_ob means

**Comment by AndrewSmithWalter** [comment]
@wenbowen123

**Comment by wenbowen123** [comment]
it is the camera pose relative to the object

**Comment by jingchenlu** [comment]
How do I get the com_in_ob folder based on rgb and mask

**Comment by jingchenlu** [comment]
@AndrewSmithWalter Have you solved this problem, how can you let me know, I would be very grateful

**Comment by jingchenlu** [comment]
@AndrewSmithWalter Have you solved this problem? I would be very grateful if you could let me know !

**Comment by kxlnx** [comment]
> [@AndrewSmithWalter](https://github.com/AndrewSmithWalter) Have you solved this problem? I would be very grateful if you could let me know !

May I ask if you know how to obtain cam_in_ob? I also encountered the same problem

**Comment by jingchenLu** [comment]
@kxlnx It's been a while and I've somewhat forgotten. I obtained the object modeling and the posture of the object relative to the camera through his other work, BundleSDF.

**Comment by kxlnx** [comment]
多谢回复



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 21, 2025 12:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVlabs/FoundationPose] what's the meaning of cam_in_ob (Issue#96)


jingchenlu left a comment (NVlabs/FoundationPose#96)
 
@kxlnx It's been a while and I've somewhat forgotten. I obtained the object modeling and the posture of the object relative to the camera through his other work, BundleSDF.
