### ISSUE TITLE
Training Data - How to use?

### ISSUE THREAD

**Issue by lashout314** [NVlabs/FoundationPose#99]
@wenbowen123 Thanks for your great work!  I'm trying to fine-tune the Refinement and Selection models to use RGB input only using the training data you provided.

It appears the training dataset consists of pairs of renders of the same scene with bbox, K, distance to image plane, instance segmentation, and RGB render.  Do you utilize one of the pair as the rendering and the other as the input observation for the pose refinement training?

It would be great if you could describe how the training dataset you provide is used.

**Comment by wenbowen123** [comment]
Hi, each scene is independent. To make the training pairs, you need to implement this yourself, by following the paper. We do not support the training part in the repo at the moment.
